### ISSUE TITLE
ci.onarandombox.com is down?

### ISSUE THREAD

**Issue by Gladles** [Multiverse/Multiverse-Core#2347] opened 2020-07-15 05:49 UTC
I need 1.16.1 Multiverse-core.. but website is down. please restart.

**Comment by nicegamer7** [comment] 2020-07-15 13:39
Yes, we're aware. I'm closing this as a duplicate of #2323. For now, we've uploaded the latest CI builds to our Discord server.

**Closed by nicegamer7** 2020-07-15 13:39 UTC
