### ISSUE TITLE
doImmediateRespawn not effective after restart

### ISSUE THREAD

**Issue by JasonHorkles** [Multiverse/Multiverse-Core#2251] opened 2020-05-06 21:40 UTC
For some reason doImmediateRespawn doesn't like working - like it works for a bit and then when I restart the server it seems to turn back off again
I've been using /gamerule and /mvrule yet it still doesn't seem to keep the changes
The gamerule will remain as true, but it multiverse is seeming to be overriding it as it doesn't work unless I do the mvrule command again

**Comment by nicegamer7** [comment] 2020-05-07 19:17
I'm able to reproduce this using the steps outlined above (although, restarting the server is unnecessary). I'm not sure if this is an issue that relates to Multiverse since Multiverse doesn't handle gamerules (the server does), but I'm looking into it.

**Comment by nicegamer7** [comment] 2020-05-07 21:55
I've filed a bug report [here](https://hub.spigotmc.org/jira/browse/SPIGOT-5727).

**Comment by JasonHorkles** [comment] 2020-05-07 21:57
Awesome thank you!

**Comment by nicegamer7** [comment] 2020-05-10 01:47
The bug has been fixed! I'll close this issue once the fix makes it to Paper.

**Comment by nicegamer7** [comment] 2020-05-12 18:49
The fix is in Paper as of build #282. Thanks for reporting :)

**Closed by nicegamer7** 2020-05-12 18:49 UTC
Labels: Bug, Unrelated to MV
