### ISSUE TITLE
Error about entity create portal

### ISSUE THREAD

**Issue by Barroncz** [Multiverse/Multiverse-Core#2316] opened 2020-06-29 19:10 UTC
This error shows me always and i dont know why... 
[21:04:17 WARN]: [Multiverse-Core] "Multiverse-Core v4.1.0-b775" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

**Comment by nicegamer7** [comment] 2020-06-29 19:12
Hey no need to worry, see the line right below that! Closing as a duplicate of #2000.

**Closed by nicegamer7** 2020-06-29 19:12 UTC
