### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Restond** [Multiverse/Multiverse-Core#3083] opened 2024-08-10 04:24 UTC
### `/mv version -p` output

None

### Server logs

None

### Server Version

```shell
Paper1.20.1-196
```

### Bug Description

[12:16:02 WARN]: [Multiverse-Core] "Multiverse-Core v4.3.12" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].

However, it does not affect the use.

### Steps to reproduce

Start.bat

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [x] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by zax71** [comment] 2024-08-11 18:08
Duplicate of #2000

**Closed by zax71** 2024-08-11 18:08 UTC
Labels: Bug: Unconfirmed
