### ISSUE TITLE
Deprecated method error.

### ISSUE THREAD

**Issue by Kimpstheman** [Multiverse/Multiverse-Core#2031] opened 2019-06-28 12:23 UTC
When starting up the server, multiverse core gives a deprecated method error:

https://pastebin.com/SymhuS9V

Using latest release.

Running Paper 1.14.3 #117 build

**Comment by Tresswa** [comment] 2019-06-29 03:04
I have noticed this same error at start up.

**Comment by Jadiction** [comment] 2019-06-29 21:14
Duplicate of https://github.com/Multiverse/Multiverse-Core/issues/2000

**Closed by Jadiction** 2019-06-29 21:14 UTC
Labels: Duplicate
