### ISSUE TITLE
Main world overrides any structure-gen settings for other worlds. (1.16.1)

### ISSUE THREAD

**Issue by geekywookie95** [Multiverse/Multiverse-Core#2339] opened 2020-07-08 23:34 UTC
I have a flat, no structure generation hub world as my server.properties level-name main world. This is, unfortunately, overriding other settings. For example, when I create a new end, no end cities generate. (The gateway portals also don't work, but this is likely a mojang issue.) I'm guessing that this is a multiverse bug.

**Comment by NobleStrike** [comment] 2020-07-09 00:03
I have the same issue. As of 1.16 if the server.properties is set to a main world with structures disabled it overrides all worlds (nether and end too), regardless of their individual world settings in their nbt files. It does place the cords for the structures however, you can see them with /locate but they just arent generated. The issue can be worked around by using a main world with structures enabled, however many of us use flat worlds with it disabled as our spawns/hubs. And changing the structure setting isnt easy at all it seems its all rooted deep into the nbt beyond my understanding.

I hope to just see a setting in multiverse to enable or disable structure generation in a world individually. For basic vanilla servers i can see why the main world controls all other worlds structure settings for simplicity, but that creates issues for some of us.

Thank you for the help!

**Comment by nicegamer7** [comment] 2020-07-09 03:54
I'm going to close this as a duplicate of #2310.

P.S. Thanks @NobleStrike for looking into this.

**Closed by nicegamer7** 2020-07-09 03:54 UTC
