### ISSUE TITLE
Multiverse and Bukkit Settings are Different (1.16)

### ISSUE THREAD

**Issue by csev1755** [Multiverse/Multiverse-Core#2318] opened 2020-06-29 21:09 UTC
I've found that after updating to 1.16.1, monsters are no longer spawning in any of my worlds. When I change it back with the /mv modify set command, it reverts back on a server restart. The Multiverse Setting is always true, but the Bukkit Setting gets reset with every restart.
```
[15:45:16 INFO]: --- Monster Settings ---
[15:45:16 INFO]: Multiverse Setting: true
[15:45:16 INFO]: Bukkit Setting: false
[15:45:16 INFO]: Monsters that CAN spawn: ALL

```

**Comment by Phoenix616** [comment] 2020-06-30 16:05
The bukkit setting stems from the server.properties/bukkit.yml or a different plugin changing that via the api. Did you test without any other plugin and the default configs?

**Comment by asterism-s** [comment] 2020-07-02 09:41
This is happening to me too, our server is live so I'm not able to remove everything and test. Every time I restart the server, mob spawning stops in all of our worlds. The settings in multiverse worlds.yml are always set to true. I'm not sure how to access the monster settings shown above. Would appreciate any thoughts/solutions :)

**Comment by Brokkonaut** [comment] 2020-07-04 03:50
I can confirm this is happening in 1.16. Not sure if its a server bug or some plugin is resetting the value.

Strangely for some worlds on my server the setting was synced, but for some other worlds it is not.
"/mv reload" helps to sync the mob spawning settings, but currently i have to use it after every server start.

**Comment by twiceineverymoment** [comment] 2020-07-23 15:01
Can confirm, this exact same thing is happening on my server too. Server.properties has spawn-monsters=true. Using /mv reload fixes the issue but restarting the server causes it to come up again. I can use /mv info 3 to see the multiverse setting for monsters is true but the bukkit setting is false. I do have access to a test environment though, if we think another plugin might be causing it.

**Comment by Phoenix616** [comment] 2020-07-23 15:14
Just to provide my own two cents: This does not happen to me using Multiverse-Core 4.1.0-b775 and Paper b101.

**Comment by twiceineverymoment** [comment] 2020-07-23 15:22
> Just to provide my own two cents: This does not happen to me using Multiverse-Core 4.1.0-b775 and Paper b101.

Can you post your list of plugins? Here's mine:

Luckperms 5.1.26
AnnouncementsEverywhere 4.0.3
Vault 1.7.2-b107
Multiverse-Core 4.1.0-b775
MassiveCore 3.3.0
WorldEdit 7.2.0-beta2
EssentialsX 2.18.0.0
Multiverse-Inventories 3.0.0-b459
EssentialsXChat 2.18.0.0
EssentialsXAntiBuild 2.18.0.0
PVPArena 1.14.0
Multiverse-Portals 4.1.0-b805
WorldGuard 7.0.3;5407315
Factions 3.3.0
EssentialsXProtect 2.18.0.0
Multiverse-NetherPortals 4.1.0-b763

**Comment by Phoenix616** [comment] 2020-07-23 15:30
> Can you post your list of plugins?

No, they are too many (and mostly not even widely used/public so the list itself would be pointless) and have nothing to do with your bug as none of my plugins touches that setting.

Out of your plugins I don't use the following though so maybe test without them (and with Paper):
AnnouncementsEverywhere 4.0.3
MassiveCore 3.3.0
Multiverse-Inventories 3.0.0-b459
EssentialsXChat 2.18.0.0
EssentialsXAntiBuild 2.18.0.0
PVPArena 1.14.0
Factions 3.3.0
EssentialsXProtect 2.18.0.0

**Comment by twiceineverymoment** [comment] 2020-07-23 17:16
I removed all plugins in my test env except Multiverse-Core, used the latest Paper build (#110), and still have the same issue.
You can see the value changing in the attached log snippet. This is right after startup completes, and no players are connected.

`>mv info factions
[11:07:25] [Server thread/INFO]: --- General Info ---
[11:07:25] [Server thread/INFO]: World Name: factions
[11:07:25] [Server thread/INFO]: World Alias: &c<&6Factions&c>
[11:07:25] [Server thread/INFO]: Game Mode: SURVIVAL
[11:07:25] [Server thread/INFO]: Difficulty: EASY
[11:07:25] [Server thread/INFO]: Spawn Location: X: 103.61 Y: 101 Z: -106.29 P: 10.32 Y: -39.97 
[11:07:25] [Server thread/INFO]: World Scale: 1.0
[11:07:25] [Server thread/INFO]: World Seed: 2041509194327623290
[11:07:25] [Server thread/INFO]: Price to enter this world: FREE!
[11:07:25] [Server thread/INFO]:  
[11:07:25] [Server thread/INFO]: --- More World Settings ---
[11:07:25] [Server thread/INFO]: World Type: NORMAL
[11:07:25] [Server thread/INFO]: Structures: true
[11:07:25] [Server thread/INFO]: Weather: true
[11:07:25] [Server thread/INFO]: Players will get hungry: true
[11:07:25] [Server thread/INFO]: Keep spawn in memory: true
[11:07:25] [Server thread/INFO]:  
[11:07:25] [Server thread/INFO]: --- PVP Settings ---
[11:07:25] [Server thread/INFO]: Multiverse Setting: true
[11:07:25] [Server thread/INFO]: Bukkit Setting: true
[11:07:25] [Server thread/INFO]:  
[11:07:25] [Server thread/INFO]: --- Monster Settings ---
[11:07:25] [Server thread/INFO]: Multiverse Setting: true
[11:07:25] [Server thread/INFO]: Bukkit Setting: **false**
[11:07:25] [Server thread/INFO]: Monsters that CAN spawn: ALL
[11:07:25] [Server thread/INFO]:  
[11:07:25] [Server thread/INFO]: --- Animal Settings ---
[11:07:25] [Server thread/INFO]: Multiverse Setting: true
[11:07:25] [Server thread/INFO]: Bukkit Setting: true
[11:07:25] [Server thread/INFO]: Animals that CAN spawn: ALL
>mv reload
[11:07:34] [Server thread/INFO]: Reloading all Multiverse Plugin configs...
[11:07:34] [Server thread/INFO]: [Multiverse-Core] 17 - World(s) loaded.
[11:07:35] [Server thread/INFO]: [Multiverse-Portals] 23 - Portals(s) loaded
[11:07:35] [Server thread/INFO]: Multiverse-Core - config.yml
[11:07:35] [Server thread/INFO]: Multiverse-Core - worlds.yml
[11:07:35] [Server thread/INFO]: Multiverse-Core - anchors.yml
[11:07:35] [Server thread/INFO]: Multiverse-Inventories - config.yml
[11:07:35] [Server thread/INFO]: Multiverse-Portals - portals.yml
[11:07:35] [Server thread/INFO]: Multiverse-Portals - config.yml
[11:07:35] [Server thread/INFO]: Reload Complete!
>mv info factions
[11:07:40] [Server thread/INFO]: --- General Info ---
[11:07:40] [Server thread/INFO]: World Name: factions
[11:07:40] [Server thread/INFO]: World Alias: &c<&6Factions&c>
[11:07:40] [Server thread/INFO]: Game Mode: SURVIVAL
[11:07:40] [Server thread/INFO]: Difficulty: EASY
[11:07:40] [Server thread/INFO]: Spawn Location: X: 103.61 Y: 101 Z: -106.29 P: 10.32 Y: -39.97 
[11:07:40] [Server thread/INFO]: World Scale: 1.0
[11:07:40] [Server thread/INFO]: World Seed: 2041509194327623290
[11:07:40] [Server thread/INFO]: Price to enter this world: FREE!
[11:07:40] [Server thread/INFO]:  
[11:07:40] [Server thread/INFO]: --- More World Settings ---
[11:07:40] [Server thread/INFO]: World Type: NORMAL
[11:07:40] [Server thread/INFO]: Structures: true
[11:07:40] [Server thread/INFO]: Weather: true
[11:07:40] [Server thread/INFO]: Players will get hungry: true
[11:07:40] [Server thread/INFO]: Keep spawn in memory: true
[11:07:40] [Server thread/INFO]:  
[11:07:40] [Server thread/INFO]: --- PVP Settings ---
[11:07:40] [Server thread/INFO]: Multiverse Setting: true
[11:07:40] [Server thread/INFO]: Bukkit Setting: **true**
[11:07:40] [Server thread/INFO]:  
[11:07:40] [Server thread/INFO]: --- Monster Settings ---
[11:07:40] [Server thread/INFO]: Multiverse Setting: true
[11:07:40] [Server thread/INFO]: Bukkit Setting: true
[11:07:40] [Server thread/INFO]: Monsters that CAN spawn: ALL
[11:07:40] [Server thread/INFO]:  
[11:07:40] [Server thread/INFO]: --- Animal Settings ---
[11:07:40] [Server thread/INFO]: Multiverse Setting: true
[11:07:40] [Server thread/INFO]: Bukkit Setting: true
[11:07:40] [Server thread/INFO]: Animals that CAN spawn: ALL
`

**Comment by csev1755** [comment] 2020-07-26 18:48
I'm still having the same issue in Paper #110, but /mv reload does help.

**Comment by csev1755** [comment] 2020-08-17 05:30
I decided to do some testing on a completely fresh instance of Paper #135 and Multiverse Core 4.1.0.

After installing, I tried setting the monsters to false on the initial "world" world. After a restart, it remembered the change. I then created a new overworld called "test." I set the monsters to false and reset the server. When it rebooted, it remembered the setting for "test" but not for "world." /mv reload fixed it as expected.

Hopefully someone can reproduce the problem with my steps.

**Comment by DeathChain01** [comment] 2020-09-23 23:04
I'm experiencing this too, both in git-Spigot-17d78db-f8d4da0 and Paper #204 with MV2 Core #793. It happened with Paper 202, 101, and earlier Spigot and Paper 1.16.x versions as well.

I can provide or test whatever you want.

**Comment by nicegamer7** [comment] 2020-09-23 23:10
If you've got the time, can you try it on older versions of Minecraft, like 1.15, 1.14, and 1.13?

**Comment by Brokkonaut** [comment] 2020-09-23 23:17
The issue exists since 1.16.

**Comment by nicegamer7** [comment] 2020-09-23 23:20
I just wanted to be sure that the Multiverse and Bukkit settings were the same on older versions of Minecraft.

**Comment by DeathChain01** [comment] 2020-09-23 23:25
> 
> 
> If you've got the time, can you try it on older versions of Minecraft, like 1.15, 1.14, and 1.13?

Been running MV2 Core since MC 1.8, this is the first time this problem ever manifested. Never happened in 1.15, 1.14, 1.13, or older versions.

(I can spin it up again anyway if you really want me to though.)

**Comment by nicegamer7** [comment] 2020-09-23 23:28
Actually, I'll do my own testing, an if I can't reproduce, then I'll ask for more details.

**Comment by nicegamer7** [comment] 2020-09-23 23:35
-_-

as usual, I cannot reproduce the issue on a fresh server install. Although, I don't doubt the issue exists. Can someone give me reproduction steps from a fresh server install.

P.S. I am testing on Paper Build 204, and MV Core Build 793.

**Comment by DeathChain01** [comment] 2020-09-23 23:48
> 
> 
> -_-
> 
> as usual, I cannot reproduce the issue on a fresh server install. Although, I don't doubt the issue exists. Can someone give me reproduction steps from a fresh server install.
> 
> P.S. I am testing on Paper Build 204, and MV Core Build 793.

Putting one together right now, will document the steps I take and at which point it manifests.

**Comment by DeathChain01** [comment] 2020-09-24 02:13
!!!!!  ISSUE MANIFESTS AT STEP 34  !!!!!

I think it's isolated to my MV2 configs, based on the action taken below. I've attached my config.yml and worlds.yml files as a result. These same configs were used in Spigot/Paper 1.13.x, 1.14.x, and 1.15.x without issue. Possibly a config setting that didn't matter before but does now?

[config.txt](https://github.com/Multiverse/Multiverse-Core/files/5272985/config.txt)
[worlds.txt](https://github.com/Multiverse/Multiverse-Core/files/5272986/worlds.txt)

========================
STEPS USED TO REPLICATE THE PROBLEM:

01: Placed "paper-204.jar" and "start-v2paper.bat" in the same folder (in this case named MC 1.16.03 PAPR-T).

Contents of file "start-v2paper.bat" are as such (all one line):
ava -Xms256M -Xmx10G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=50 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts -jar paper-204.jar nogui

02: Ran "start-v2paper.bat" to generate the eula.txt, which was set to "true", then reran the batch file to start it for real.

03: Logged into the server with zero plugins, observed hostile mobs spawning at night.

04: Stopped server, added MV2 Core 793, relaunched server.

05: Observed hostile mobs spawning at night.

06: Stopped server, changed difficulty to hard in "server.properties" and "./plugins/Multiverse-Core/worlds.yml" to more accurately match my own server's setup.

07: Started server, observed hostile mobs spawning at night, opped myself via console.

08: Copied server worlds "survival3" (originally generated in MC 1.10), "creative2" (originally generated in MC 1.8), "mushtown" (originally generated in Minecraft Beta 1.x), and "spawntown" (originally generated in MC Alpha 1.x) from the current production server into the root server folder alongside the default worlds.

09: Started server and ran /mvimport survival3 NORMAL. Command succeeded.

10: Ran /mvtp survival3, successfully teleported to the world, observed hostile mobs spawning at night and /mvinfo 3 shows mobs as True for both Bukkit and MV2, monster that can spawn is ALL.

11: Stopped server, relaunched server, mobs are still spawning, /mvinfo 3 still shows true for both.

12: Ran /mvimport survival3 NORMAL. Command succeeded.

13: Ran /mvtp creative2, teleported to the world, mobs are spawning properly and settings remain correct.

14: Stopped server, relaunched server, mobs are still working in all worlds.

15: Ran /mvimport mushtown NORMAL, it succeeded, ran /mvtp mushtown and successfully teleported to the world, /mvinfo 3 is correct but mobs did not spawn due to MV2 detecting the world's PEACEFUL difficulty.

16: Stopped server, changed difficulty of "mushtown" to HARD in "./plugins/Multiverse-Core/worlds.yml", relaunched server, hostile mobs now spawn.

17: Ran /mvimport spawntown NORMAL, it succeeded.

18: Ran /mvtp spawntown, successfully teleported, no mobs due to imported PEACEFUL world difficulty.

19: Changed difficulty from PEACEFUL to HARD in "./plugins/Multiverse-Core/worlds.yml", ran /mvreload, hostile mobs now spawn, /mvinfo 3 is true for both.

20: Stopped server, relaunched server, hostile mobs are still spawning in all worlds.

21: Stopped server, copied in MV2 Portals and MV2 Netherportals, launched server to egenrated configs, then stopped it and relaunched, hostile mobs are still working and /mvinfo 3 settings are still True.

22: Stopped server, copied in plugins WorldEdit 7.2.0 Beta 2 and WorldGuard 7.0.4 Beta 1, started server, mobs and settings are still working.

23: Stopped server and relaunched server, still working.

24: Stopped server, copied in plugin Luckperms 5.1.93, started server, mobs and settings are still correct.

25: Stopped server, copied in plugins AsyncWorldEdit 3.7.5 and Warpalicious 1.11, started server, mobs and settings are still correct.

26: Stopped server, copied in plugin CoreProtect 19.2, started server, mobs and settings are still correct.

27: Stopped and relaunched server, still working.

28: Stopped server, copied in EliteMobs 7.1.44, startd server, mobs and settings are still correct.

29: Stopped server, copied in plugins BetterSleeping 3.0.3 and ChopTree 2 2.4.3, started server, mobs and settings are still correct.

30: Stopped server, copied in plugins Vault 1.7.3 and Vault Chat Formatter 1.0, started server, mobs and settings are still correct.

31: Stopped server, copied in plugin OhTheDungeonsYou'llGo 7.2, started server, mobs and settings are still correct.

32: Stopped server, copied in plugin PerfectBackup 1.6, started server, mobs and settings are still correct.

33: Stopped server, copied in PerWorldInventory 2.3.2, mobs and settings are still correct. At this point, all production plugins are present in this server instance, issue has not manifested yet.

34: Deleted the MV2 Core configs and all world folders. Copied in the worlds.yml and config.yml files from the production server. Changed the "level-name" value in server.properties to "spawn". Copied in all worlds from the production server: ajproject, cachestore, cacheworld, creative, creative2, creative2_nether, creative2_the_end, em_guild, eventure1, experiments, experiments_nether, experiments_the_end, ktundra, mushtown, oceantown, pixelart, pixelart2, spawn, spawn_nether, spawn_the_end, spawntown, survival3, survival3_nether, survival3_the_end, survival3em1, wtundra. All other plugins still have their default unmodified configs.

35: Started server, survival3 mobs and settings are working fine, but creative2 and survival3em1 are not spawning mobs and the Bukkit setting is now False for both too. Running /mvreload causes the Bukkit setting to change back to True and hostile mobs immediately began spawning in both worlds.

36: Stopped server, removed all plugins except MV2 Core, MV2 Portals, MV2 Netherportals, and PerWorldInventory by moving their .jar files into a ./!REDACTED folder. Started server, Bukkit setting is back to False for both creative2 and survival3em1, no mobs are spawning. Ran /mvreload, mobs and settings are fixed again.

37: Stopped server, removed PerWorldInventory, MV2 Portals, and MV2 Netherportals, started server, creative2 and survival3em1 Bukkit settings are back to False. Running /mvreload fixed it again as usual. At this point, MV2 Core build 793 with my own configs is the only plugin the server is running. The creative2 world didn't exhibit the problem when newly imported earlier, only when the original configs were copied in and it was recopied, but the configs also brought in a pile of other worlds as well.

**Comment by DeathChain01** [comment] 2020-09-25 04:10
Did a little bit more testing. Spinning up a new server and only installing MV2 and copying in my production server's worlds and MV2 configs causes the behavior to happen as well, which can be aligned as steps 01 to 07, then 34 to 37 in the previous message.

**Comment by Xetaxheb** [comment] 2020-09-25 11:28
maybe this is somehow related to the 1.16 mojang stupidity where main level-name is actually "minecraft:overworld" now and all the associated issues; perhaps bukkit is defaulting to monsters false on non-main worlds and isn't saving references/preferences to other worlds properly because of this change? could be a bukkit bug then 

what limited info i've seen, here: https://github.com/Multiverse/Multiverse-NetherPortals/issues/173#issuecomment-678583422

**Comment by DeathChain01** [comment] 2020-09-25 21:40
Also happens using git-Spigot-17d68db-f8d4da0, using same short method described in my previous comment.

**Comment by Phoenix616** [comment] 2020-09-25 22:13
> The creative2 world didn't exhibit the problem when newly imported earlier, only when the original configs were copied in

Did you check if there were any differences in the world's config section?

**Comment by DeathChain01** [comment] 2020-09-26 00:18
> 
> 
> > The creative2 world didn't exhibit the problem when newly imported earlier, only when the original configs were copied in
> 
> Did you check if there were any differences in the world's config section?

I want to say I checked that a while back and found nothing of consequence, bit I don't remember for sure so I did it again. Only different settings are as such:

ORIGINAL CONFIG:
alias: 'creative2'
respawnWorld: 'creative2'
gameMode: CREATIVE

NEWLY IMPORTED CONFIG:
alias: ''
respawnWorld: ''
gameMode: SURVIVAL

(The "alias" and "respawnWorld" settings are just '' as there is nothing between the two apostrophes, as is normal for a blank default MV2 world setting.)

**Comment by nicegamer7** [comment] 2020-10-22 04:02
I was able to reproduce the issue using the instructions given [here](https://github.com/Multiverse/Multiverse-Core/issues/2318#issuecomment-674664218). Will be investigating some more.

**Comment by nicegamer7** [comment] 2020-10-22 05:50
I've reported this issue to Spigot with a simple plugin that demonstrates the bug:
https://hub.spigotmc.org/jira/browse/SPIGOT-6197

**Comment by nicegamer7** [comment] 2020-11-06 08:32
This has just been fixed by Spigot. If someone could please confirm it's working for them by building the latest version of Spigot using BuildTools it would be appreciated.

**Comment by csev1755** [comment] 2020-11-07 00:37
> I was able to reproduce the issue using the instructions given [here](https://github.com/Multiverse/Multiverse-Core/issues/2318#issuecomment-674664218). Will be investigating some more.

I just tested this out using the instructions I provided on Paper 261 and the latest Spigot from BuildTools (git-Spigot-37d799b-bc6a175). I'm using Multiverse-Core-4.2.2

It worked perfectly on Spigot but it did not work on Paper. Here's every command I typed starting from a fresh server instance with only Multiverse installed. This was actually done entirely in the terminal and I never entered the server as a player. 

```
mvm set monsters false world
mvinfo world ## multiverse and bukkit settings for monsters are both false
stop

mvinfo world ## multiverse and bukkit settings for monsters are both false
mv create test normal
mvm set monsters false test
mvinfo test ## multiverse and bukkit settings for monsters are both false
mvinfo world ## in Paper, the multiverse setting remains false but the bukkit setting is now true
stop

mvinfo world ## in Spigot, the settings remain the same from last boot. In Paper, the Bukkit setting is still set to true
mvinfo test ## no change for the test world on either servers
mvm set monsters false world ## i decided to try and set monsters back to false instead of /mvreload
mvinfo world ## multiverse and bukkit settings for monsters are both false again
stop

mvinfo world ## in Paper, the Bukkit sets itself back to true again after reboot
mvinfo test ## the settings for this world never change

```
Hopefully I was able to add a little extra helpful info.

**Comment by Brokkonaut** [comment] 2020-11-07 00:39
Afaik Paper fixed the issue in Build 262

**Comment by nicegamer7** [comment] 2020-11-07 00:44
@Brokkonaut is correct, Paper Build 262 incorporates this fix. Thanks for everyone who participated!

**Closed by nicegamer7** 2020-11-07 00:44 UTC
Labels: Bug: Confirmed, Resolution: Unrelated to MV, Severity: Critical
