### ISSUE TITLE
crashes server, was told to report by plugin

### ISSUE THREAD

**Issue by nullbulous** [Multiverse/Multiverse-Core#2076] opened 2019-08-16 20:04 UTC
using free aeternos server so ram is... limited
bug is as follows as reported by log
[15:50:42] [Server thread/WARN]: [Multiverse-Core] "Multiverse-Core v2.5-b719" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--].

server ends up running consistantly 230 ticks behind and crashes if someone joins during this lag spike

**Comment by Jadiction** [comment] 2019-08-17 04:10
Duplicate of #2000 
The performance affected isn't noticeable.

**Closed by Jadiction** 2019-08-17 04:10 UTC
Labels: Duplicate
