### ISSUE TITLE
[Bug]: Multiverse-Core lags server

### ISSUE THREAD

**Issue by le0nlol** [Multiverse/Multiverse-Core#3122] opened 2024-11-03 17:20 UTC
### `/mv version -p` output

[20:14:54 INFO]: [Multiverse-Core] Multiverse-Core Version: 4.3.13 [20:14:54 INFO]: [Multiverse-Core] Bukkit Version: 1.21-130-b1b5d4c (MC: 1.21) [20:14:54 INFO]: [Multiverse-Core] Loaded Worlds: [{"MVWorld@1671598906":{"Gen":"null","Type":"NORMAL","Env":"THE_END","Name":"world_the_end"}}, {"MVWorld@1679487306":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world"}}, {"MVWorld@1012331824":{"Gen":"null","Type":"NORMAL","Env":"NETHER","Name":"world_nether"}}, {"MVWorld@399703826":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"first"}}] [20:14:54 INFO]: [Multiverse-Core] Multiverse Plugins Loaded: 0 [20:14:54 INFO]: [Multiverse-Core] Economy being used: EssentialsX Economy [20:14:54 INFO]: [Multiverse-Core] Permissions Plugin: Bukkit Permissions (SuperPerms) [20:14:54 INFO]: [Multiverse-Core] Dumping Config Values: (version 2.9) [20:14:54 INFO]: [Multiverse-Core]   enforceaccess: false [20:14:54 INFO]: [Multiverse-Core]   prefixchat: false [20:14:54 INFO]: [Multiverse-Core]   prefixchatformat: [%world%]%chat% [20:14:54 INFO]: [Multiverse-Core]   useasyncchat: true [20:14:54 INFO]: [Multiverse-Core]   teleportintercept: true [20:14:54 INFO]: [Multiverse-Core]   firstspawnoverride: true [20:14:54 INFO]: [Multiverse-Core]   displaypermerrors: true [20:14:54 INFO]: [Multiverse-Core]   enablebuscript: false [20:14:54 INFO]: [Multiverse-Core]   globaldebug: 0 [20:14:54 INFO]: [Multiverse-Core]   silentstart: false [20:14:54 INFO]: [Multiverse-Core]   messagecooldown: 5000 [20:14:54 INFO]: [Multiverse-Core]   version: 2.9 [20:14:54 INFO]: [Multiverse-Core]   firstspawnworld: world [20:14:54 INFO]: [Multiverse-Core]   teleportcooldown: 1000 [20:14:54 INFO]: [Multiverse-Core]   defaultportalsearch: true [20:14:54 INFO]: [Multiverse-Core]   portalsearchradius: 128 [20:14:54 INFO]: [Multiverse-Core]   autopurge: true [20:14:54 INFO]: [Multiverse-Core] Special Code: FRN002

### Server logs

https://mclo.gs/QfwTcOO

### Server Version

```shell
This server is running Paper version 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
```

### Bug Description

I saw that server TPS and MSPT were unstable, I checked console and saw this:

[18:23:24] [Server thread/WARN]: [Multiverse-Core] "Multiverse-Core v4.3.13" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].

### Steps to reproduce

Unknown

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by zax71** [comment] 2024-11-03 20:53
Duplicate of #2000, non issue

**Closed by zax71** 2024-11-03 20:53 UTC
Labels: Bug: Unconfirmed
