### ISSUE TITLE
Getting a WARN in 1.14.4 stating it may affect performance and to let authors know

### ISSUE THREAD

**Issue by axemwa** [Multiverse/Multiverse-Core#2048] opened 2019-07-23 07:08 UTC
Getting a WARN in 1.14.4 stating it may affect performance

Using latest dev build of MultiverseCore

[16:34:21 WARN]: [Multiverse-Core] "Multiverse-Core v4.0.0-b766" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

**Comment by dumptruckman** [comment] 2019-07-25 12:59
Duplicate of #2000.

**Closed by dumptruckman** 2019-07-25 12:59 UTC
