### ISSUE TITLE
Deprecated Event, Please Notify Authors

### ISSUE THREAD

**Issue by Stixil** [Multiverse/Multiverse-Core#2068] opened 2019-08-08 04:32 UTC
[00:44:50] [Server thread/WARN]: [Multiverse-Core] "Multiverse-Core v4.0.0-b766" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

**Comment by DutchUser** [comment] 2019-08-08 14:48
Is a known thing. Can be ignored. Wont impact peformance

**Comment by Jadiction** [comment] 2019-08-09 20:57
Duplicate of #2000.

**Closed by Jadiction** 2019-08-09 20:57 UTC
