### ISSUE TITLE
"mv list" map order is nonsensical?

### ISSUE THREAD

**Issue by VL4DST3R** [Multiverse/Multiverse-Core#2089] opened 2019-08-28 20:06 UTC
For the life of me i can't figure out how mv sorts the maps you import to it. I'm talking about the maps you see when you do "mv list" or inside the worlds.yml file. It seems that regardless of what order you import them, they get sorted via some arbitrary criteria i cant for the life of me figure the pattern of. It's not alphabetical, nor based on the creation date or world dimension, and if you try to manually switch them around from the worlds.yml, file, when you start the server it reverts back to the initial order.

**Comment by timriker** [comment] 2019-09-04 05:24
Dupe #1960 ?

**Comment by VL4DST3R** [comment] 2019-09-04 05:36
Well, technically i wasn't just pointing it out that it happens, i know it's been mentioned in #1960 already, i was trying to get more info about HOW it currently sorts the worlds you import, and hopefuly  find a way around it (say, with a prefix or numbering the worlds or something).

**Comment by nicegamer7** [comment] 2020-06-05 02:42
I believe this is due to the fact that WorldManager uses a ConcurrentHashMap to store the worlds, which is unordered.

**Comment by benwoo1110** [comment] 2020-10-06 15:17
Close as its duplicate of #1960

**Closed by benwoo1110** 2020-10-06 15:17 UTC
Labels: Assistance
