### ISSUE TITLE
[Idea]: DataPacks for Individual Worlds

### ISSUE THREAD

**Issue by sabs-shep886** [Multiverse/Multiverse-Core#3039] opened 2023-10-08 15:08 UTC
### Describe the feature

Right so Ik this is a big ask, but for example If you wanted a server where multiple worlds have different features for example U could have an Aether Datapack For one and another Custom Portal Datapack on another. Well I think you get my point. If this is already a feature Please Just like inform me, If not Ik its a big ask but it would be amazing

### How is the feature useful to all Multiverse users?

I think I already Explained It would Just be handy

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by zax71** [comment] 2023-10-09 17:29
Duplicate of #2761

**Closed by zax71** 2023-10-09 17:29 UTC
Labels: Type: Idea
