### ISSUE TITLE
You can fall through the world and die when spectating players in other worlds in spectator mode

### ISSUE THREAD

**Issue by Kruize1** [Multiverse/Multiverse-Core#2653] opened 2021-06-26 05:10 UTC
### Information

* **Server version:** 
This server is running Paper version git-Paper-772 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

* **Full output of `/mv version -p`:** 
https://pastebin.com/9K0eDs07

* **Server log:**
https://gist.github.com/Kruize1/8264301f6db560b100e47a268498f120

### Details
I was **`not able`** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
Entering Spectator Mode, and spectating a user in another world, kills you

**Steps to reproduce**  
1. Ensure you are OP
2. Ensure you create a new world (example: "world_gold")
3. In "world" set gamemode to survival
4. In "world_gold" set gamemode to survival
5. Go back to "world"
6. Ensure there is a player in "world_gold"
7. While in "world" , set your gamemode to spectator
8. Teleport to player with number keys on keyboard or use /tp command (ex. /tp player1 player2)
9. Observe and note that you fall through solid blocks, like you're ethereal like spectator mode, but have gravity like survival

**Expected behavior**  
You should retain spectator mode and you shouldn't fall through the world 
Note: This happens with other combinations, like Creative mode but you can't fly, and Survival mode but you can fly.

**Screenshots**  
https://clips.twitch.tv/InexpensiveFunnyOxFloof-xAmgvKQX5np4hyPT

**Comment by benwoo1110** [comment] 2021-06-26 05:12
MV doesn't alter spectator mode at all. Sounds like a 1.17 bug.

**Comment by benwoo1110** [comment] 2021-06-28 03:49
Can't reproduce the issue on the latest paper version. I suggest testing with only mv plugin installed.

**Comment by benwoo1110** [comment] 2021-07-21 09:54
Closing as can't reproduce and no further response from the author. Feel free to open a new issue if needed.

**Closed by benwoo1110** 2021-07-21 09:54 UTC
Labels: Bug: Can't Reproduce
