### ISSUE TITLE
regex spam

### ISSUE THREAD

**Issue by minhowow** [Multiverse/Multiverse-Core#2711] opened 2021-09-23 09:43 UTC
### Information

* **Server version:** 
This server is running Airplane version git-Airplane-"ec7d3d0" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: ec7d3d0 on HEAD)
Unknown version
Previous version: git-Airplane-"a216fc0" (MC: 1.17.1)

* **Full output of `/mv version -p`:** 
https://j.mp/3nYU4de
* **Server log:** 
<removed>
### Details
I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  

regex overloading issue

**Steps to reproduce**  

just run the command below
any player can run this command
after running this command, server will be stopped

**Expected behavior**  

server paused or stopped

**Screenshots**  
<removed>

**Comment by benwoo1110** [comment] 2021-09-23 09:47
Duplicate of #2703.

**Closed by benwoo1110** 2021-09-23 09:47 UTC
Labels: Bug: Unconfirmed
