### ISSUE TITLE
Someone come into my server and type mv command and server crash

### ISSUE THREAD

**Issue by xxmethaa** [Multiverse/Multiverse-Core#2709] opened 2021-09-22 16:14 UTC
[22:59:30] [Server thread/INFO]: _METHAA issued server command: /mv ^(.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.++)$^
[22:59:40] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Purpur-1171 (MC: 1.16.5) ---
[22:59:40] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
[22:59:40] [Paper Watchdog Thread/ERROR]: ------------------------------
[22:59:40] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[22:59:40] [Paper Watchdog Thread/ERROR]: Ticking entity: minecraft:player, entity class: net.minecraft.server.v1_16_R3.EntityPlayer
[22:59:40] [Paper Watchdog Thread/ERROR]: Entity status: dead: false, valid: true, alive: true, is passenger: false
[22:59:40] [Paper Watchdog Thread/ERROR]: Entity UUID: 0eeb01dd-6970-3cc3-ba56-0df4de36ce06
[22:59:40] [Paper Watchdog Thread/ERROR]: Position: world: 'world' at location (759.3251971912381, 4.0, -19.868694788546062)
[22:59:40] [Paper Watchdog Thread/ERROR]: Velocity: (0.0, -0.0784000015258789, 0.0) (in blocks per tick)
[22:59:40] [Paper Watchdog Thread/ERROR]: Entity AABB: AABB[759.0251971793172, 4.0, -20.16869480046699] -> [759.625197203159, 5.799999952316284, -19.568694776625133]
[22:59:40] [Paper Watchdog Thread/ERROR]: Total packets processed on the main thread for all players: 1476
[22:59:40] [Paper Watchdog Thread/ERROR]: ------------------------------
[22:59:40] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[22:59:40] [Paper Watchdog Thread/ERROR]: 	PID: 30 | Suspended: false | Native: false | State: RUNNABLE
[22:59:40] [Paper Watchdog Thread/ERROR]: 	Stack:
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4293)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4302)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4302)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4302)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4302)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4302)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4302)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4302)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4302)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4302)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4302)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4302)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4302)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4302)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4302)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4302)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4302)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4302)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4302)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4302)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4302)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4302)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$GroupHead.match(Pattern.java:4801)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$Begin.match(Pattern.java:3684)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4302)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Matcher.match(Matcher.java:1755)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Matcher.matches(Matcher.java:712)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.util.regex.Pattern.matches(Pattern.java:1176)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.lang.String.matches(String.java:2042)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		com.onarandombox.MultiverseCore.commands.HelpCommand.getFilteredItems(HelpCommand.java:46)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		com.onarandombox.MultiverseCore.commands.HelpCommand.runCommand(HelpCommand.java:79)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:296)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:839)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		app//org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		app//org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		app//org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2315)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2130)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2083)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R3.PlayerConnectionUtils$$Lambda$7121/0x000000080242a8e0.run(Unknown Source)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1339)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1332)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1308)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1152)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3180/0x0000000801337120.run(Unknown Source)
[22:59:40] [Paper Watchdog Thread/ERROR]: 		java.base@16.0.2/java.lang.Thread.run(Thread.java:831)
[22:59:40] [Paper Watchdog Thread/ERROR]: ------------------------------

**Comment by nicegamer7** [comment] 2021-09-22 16:14
Duplicate of #2703.

**Closed by nicegamer7** 2021-09-22 16:14 UTC
Labels: Type: Assistance
