### ISSUE TITLE
worldborder doesn't work

### ISSUE THREAD

**Issue by JxM-92** [Multiverse/Multiverse-Core#2465] opened 2020-10-22 00:39 UTC
ok, I have a server with 3 overworld worlds, 1 lobby and 2 other overworld worlds...
in world lobby worldborder works, but in the other ones the border is set at size 2048 but when doing `/worldborder get` it says the size is 1000000... so I don't understand why is that... I tried using `/execute in [world] run worldborder set 1000000` but it doesn't work, even after restarting...

**Comment by benwoo1110** [comment] 2020-10-22 10:31
Duplicate of #1776

**Closed by benwoo1110** 2020-10-22 10:31 UTC
