### ISSUE TITLE
Problem with the plugin

### ISSUE THREAD

**Issue by Ougawa** [Multiverse/Multiverse-Core#1688] opened 2016-03-23 17:02 UTC
First, sorry for my bad English .
I have a problem with this plugin. Since i updated my server on 1.9, my players always have the "saturation' effect and they can't lose their food-bar. After many tests, i know now this is multiverse who is the cause of this bug.

Could you please help me ?

**Comment by leasoncre** [comment] 2016-03-23 22:05
have you updated to the latest dev version?

**Comment by Ougawa** [comment] 2016-03-23 22:20
Yeah, i updated it from here: http://ci.onarandombox.com/job/Multiverse-Core/

**Comment by dumptruckman** [comment] 2016-03-24 04:25
The only way this would be caused by Multiverse is if hunger is set to false for the world in question. There is literally no other reason for Multiverse to be causing this issue. You can find out if hunger is false by checking `/mv info`. You can set it to true while in the world by typing `/mvm set hunger true`. If that doesn't cause hunger to work normally then the problem is not related to Multiverse.

If you can provide additional details on how Multiverse would otherwise be the cause I will reopen the issue.

**Comment by Ougawa** [comment] 2016-03-24 17:16
Yes, it's related to Multiverse.
I deactivated all my plugins and reactivated them 1 per 1, that's how i know the cause is Multiverse and not an other plugin.

**Comment by Ougawa** [comment] 2016-03-24 19:09
With only multiverse:
http://www.noelshack.com/2016-12-1458846312-2016-03-24-19-59-40.png
http://www.noelshack.com/2016-12-1458846316-2016-03-24-19-59-48.png

Without Multiverse:
http://www.noelshack.com/2016-12-1458846335-2016-03-24-20-02-07.png
http://www.noelshack.com/2016-12-1458846316-2016-03-24-20-02-12.png

**Comment by dumptruckman** [comment] 2016-03-24 21:20
Well, you'd think that this would be pretty good evidence that Multiverse is causing you to have the Saturation effect all the time, however, I'm not sure how to help you here because there is nothing in Multiverse that would do this unless, as I said before, you had your world set to `hunger: true`. Can you provide us with your `worlds.yml` file contents please? You can paste it [here](https://gist.github.com/) then just give us the link. Also, what is the name of the world you are doing this in?

**Comment by dumptruckman** [comment] 2016-03-24 21:22
Also, run `/mv version -g` and give us the link it provides you with please.

**Comment by dumptruckman** [comment] 2016-03-24 21:24
Also, even in worlds where I have `hunger: true` I am not able to reproduce this issue.

**Comment by Ougawa** [comment] 2016-03-24 22:45
This is the first time i have this problem. 
In 1,8 everything was working perfectly and i didn't modified the config..

https://gist.github.com/Ougawa/2640ee08954af26c56af

and when i do /mv version -g, this is what i receive:

22:39:12 Multiverse-Core: [Multiverse-Core] Multiverse-Core Version: 2.5-b717
22:39:12 Multiverse-Core: [Multiverse-Core] Bukkit Version: git-Spigot-0426685-4cd46b2 (MC: 1.9)
22:39:12 Multiverse-Core: [Multiverse-Core] Loaded Worlds: [{"MVWorld@321380112":{"Env":"NORMAL","Name":"aabb","Type":"FLAT","Gen":"null"}}, {"MVWorld@514170179":{"Env":"NORMAL","Name":"MapTest","Type":"FLAT","Gen":"null"}}, {"MVWorld@184002925":{"Env":"THE_END","Name":"End","Type":"NORMAL","Gen":"null"}}, {"MVWorld@160708795":{"Env":"NORMAL","Name":"Eventhard","Type":"LARGE_BIOMES","Gen":"null"}}, {"MVWorld@1339952547":{"Env":"NORMAL","Name":"Spawn1","Type":"LARGE_BIOMES","Gen":"null"}}, {"MVWorld@1665256474":{"Env":"NORMAL","Name":"MondeRessource1","Type":"NORMAL","Gen":"null"}}, {"MVWorld@614177531":{"Env":"NORMAL","Name":"SpawnRessource","Type":"LARGE_BIOMES","Gen":"null"}}, {"MVWorld@1693685761":{"Env":"THE_END","Name":"world_the_end","Type":"NORMAL","Gen":"null"}}, {"MVWorld@653504923":{"Env":"NETHER","Name":"world_nether","Type":"NORMAL","Gen":"null"}}, {"MVWorld@1564634758":{"Env":"NORMAL","Name":"world","Type":"FLAT","Gen":"null"}}, {"MVWorld@936598884":{"Env":"NORMAL","Name":"HyperFractal","Type":"FLAT","Gen":"null"}}, {"MVWorld@728005055":{"Env":"NORMAL","Name":"bbcc","Type":"FLAT","Gen":"null"}}, {"MVWorld@1645773286":{"Env":"NORMAL","Name":"tetedemort","Type":"FLAT","Gen":"null"}}, {"MVWorld@922244442":{"Env":"NORMAL","Name":"EventHardcore","Type":"LARGE_BIOMES","Gen":"null"}}]
22:39:12 Multiverse-Core: [Multiverse-Core] Multiverse Plugins Loaded: 1
22:39:12 Multiverse-Core: [Multiverse-Core] Economy being used: iConomy 7
22:39:12 Multiverse-Core: [Multiverse-Core] Permissions Plugin: Bukkit Permissions (SuperPerms)
22:39:12 Multiverse-Core: [Multiverse-Core] Dumping Config Values: (version 2.9)
22:39:12 Multiverse-Core: [Multiverse-Core] messagecooldown: 5000
22:39:12 Multiverse-Core: [Multiverse-Core] teleportcooldown: 1000
22:39:12 Multiverse-Core: [Multiverse-Core] worldnameprefix: false
22:39:12 Multiverse-Core: [Multiverse-Core] worldnameprefixFormat: [%world%]%chat%
22:39:12 Multiverse-Core: [Multiverse-Core] enforceaccess: false
22:39:12 Multiverse-Core: [Multiverse-Core] displaypermerrors: true
22:39:12 Multiverse-Core: [Multiverse-Core] teleportintercept: true
22:39:12 Multiverse-Core: [Multiverse-Core] firstspawnoverride: true
22:39:12 Multiverse-Core: [Multiverse-Core] firstspawnworld: world
22:39:12 Multiverse-Core: [Multiverse-Core] debug: 0
22:39:12 Multiverse-Core: [Multiverse-Core] Special Code: FRN002
22:39:12 Multiverse-Core: [Multiverse-Portals] Multiverse-Portals Version: 2.5-b725
22:39:12 Multiverse-Core: [Multiverse-Portals] Loaded Portals: 18
22:39:12 Multiverse-Core: [Multiverse-Portals] Dumping Portal Values: (version 2.7)
22:39:12 Multiverse-Core: [Multiverse-Portals] wand: 271
22:39:12 Multiverse-Core: [Multiverse-Portals] useonmove: true
22:39:12 Multiverse-Core: [Multiverse-Portals] enforceportalaccess: true
22:39:12 Multiverse-Core: [Multiverse-Portals] portalsdefaulttonether: false
22:39:12 Multiverse-Core: [Multiverse-Portals] portalcooldown: 1000
22:39:12 Multiverse-Core: [Multiverse-Portals] clearonremove: false
22:39:12 Multiverse-Core: [Multiverse-Portals] Special Code: FRN001

**Comment by dumptruckman** [comment] 2016-03-25 03:02
Upgrade Spigot perhaps. Still nothing I can see going wrong in MV.

**Comment by Ougawa** [comment] 2016-03-29 17:23
So,
I updated Spigot to the latest version. 
I tried after that to try to put craftbukkit instead of spigot on my server.
I tried to put on my server Multiverse in a older version.

I still have this fucking problem.

**Comment by Ougawa** [comment] 2016-03-29 17:26
I used the commande /mv debug 3 and see this:

19:23:23 Multiverse-Inventories-Debug: Persisted: ender_chest, inventory_contents, armor_contents, hit_points, remaining_air, maximum_air, fall_distance, fire_ticks, xp, lvl, total_xp, food_level, exhaustion, saturation, bed_spawn, potion_effects to WORLD:world (ProfileType:SURVIVAL) for player ThalionPIR
19:23:23 Multiverse-Inventories-Debug: Ignoring optional share: economy
19:23:23 Multiverse-Inventories-Debug: got data folder: plugins\Multiverse-Inventories\worlds\world from type: WORLD
19:23:23 Multiverse-Inventories-Debug: Ignoring optional share: last_location
19:23:23 Multiverse-Inventories-Debug: got data folder: plugins\Multiverse-Inventories\worlds\world from type: WORLD
19:23:23 Multiverse-Inventories-Debug: Persisted: hit_points, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, ender_chest to GROUP:default (ProfileType:SURVIVAL) for player ThalionPIR
19:23:23 Multiverse-Inventories-Debug: Ignoring optional share: last_location
19:23:23 Multiverse-Inventories-Debug: Ignoring optional share: economy
19:23:23 Multiverse-Inventories-Debug: Defaulted: ender_chest, inventory_contents, armor_contents, hit_points, remaining_air, maximum_air, fall_distance, fire_ticks, xp, lvl, total_xp, food_level, exhaustion, saturation, bed_spawn, potion_effects for ThalionPIR for WORLD:Spawn1 (ProfileType:SURVIVAL)

Do you have an idea now ?

**Comment by Ougawa** [comment] 2016-03-29 17:40
I tried to replace MultiInv by Multiverse-Inventories
I used the commande /mv debug 3 and see this:

19:23:23 Multiverse-Inventories-Debug: Persisted: ender_chest, inventory_contents, armor_contents, hit_points, remaining_air, maximum_air, fall_distance, fire_ticks, xp, lvl, total_xp, food_level, exhaustion, saturation, bed_spawn, potion_effects to WORLD:world (ProfileType:SURVIVAL) for player ThalionPIR
19:23:23 Multiverse-Inventories-Debug: Ignoring optional share: economy
19:23:23 Multiverse-Inventories-Debug: got data folder: plugins\Multiverse-Inventories\worlds\world from type: WORLD
19:23:23 Multiverse-Inventories-Debug: Ignoring optional share: last_location
19:23:23 Multiverse-Inventories-Debug: got data folder: plugins\Multiverse-Inventories\worlds\world from type: WORLD
19:23:23 Multiverse-Inventories-Debug: Persisted: hit_points, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, ender_chest to GROUP:default (ProfileType:SURVIVAL) for player ThalionPIR
19:23:23 Multiverse-Inventories-Debug: Ignoring optional share: last_location
19:23:23 Multiverse-Inventories-Debug: Ignoring optional share: economy
19:23:23 Multiverse-Inventories-Debug: Defaulted: ender_chest, inventory_contents, armor_contents, hit_points, remaining_air, maximum_air, fall_distance, fire_ticks, xp, lvl, total_xp, food_level, exhaustion, saturation, bed_spawn, potion_effects for ThalionPIR for WORLD:Spawn1 (ProfileType:SURVIVAL)

Do you have an idea now ?

**Comment by dumptruckman** [comment] 2016-03-29 18:03
If the problem occurred without MultiInv present then why would switching from MultiInv to Multiverse-Inventories make any difference? I do not have any answers for you because as I said, your problem is not something Multiverse should have any hand in. I cannot reproduce the issue. If you want to see for yourself that Multiverse does not cause this issue normally, try starting up a local test server with literally only Multiverse-Core and attempting to reproduce the issue there. If you can, please let me know the steps you took to do so.

Also, Multiverse-Inventories is no longer supported. We recommend switching over to [PWI](https://www.spigotmc.org/resources/per-world-inventory.4482/) which seems to be a good replacement. PWI even offers the ability to import your data from Multiverse-Inventories.

**Comment by FernFerret** [comment] 2016-04-13 22:26
@dumptruckman what's the deal with this issue? Is it a thing? Is it not a thing?

**Comment by dumptruckman** [comment] 2016-04-13 23:13
It's not a thing as far as I can tell. I have no idea how @Ougawa is producing this. Closing unless it clearly reproducible steps can be given.

**Closed by dumptruckman** 2016-04-13 23:13 UTC
Labels: Assistance, Not enough Information
