### ISSUE TITLE
Error said to report

### ISSUE THREAD

**Issue by BeeRando** [Multiverse/Multiverse-Core#2007] opened 2019-06-01 01:17 UTC
Console has this error. 

01.06 00:30:02 [Server] Server thread/WARN "Multiverse-Core v3.0.0-SNAPSHOT-b761" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

**Comment by Jadiction** [comment] 2019-06-03 10:20
Duplicate of https://github.com/Multiverse/Multiverse-Core/issues/2000

**Closed by Jadiction** 2019-06-03 10:20 UTC
Labels: Duplicate
