### ISSUE TITLE
1.9 MV2.5-b717 forces default gamemode on world change

### ISSUE THREAD

**Issue by leasoncre** [Multiverse/Multiverse-Core#1676] opened 2016-03-11 03:25 UTC
i can't figure out why whenever anyone changes worlds they get reset back to survival(default world setting), opped or not. old-server-upgraded or blank-slate-new-server, same issue.
i've had this problem since spigot 1.9 came out and started testing it. finally got around to troubleshooting it and narrowing it down to multiverse.

Multiverse-Core version 2.5-b717
Multiverse-NetherPortals version 2.5-b708
git-Spigot-b1c1b55-7d330bc (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

no errors, debug level 3 only shows no issues, just a 'moved too quickly' warning on use of portals ...

**Comment by FernFerret** [comment] 2016-03-11 05:50
Have you looked at `bypass` permission?

References: 

* https://github.com/Multiverse/Multiverse-Core/wiki/FAQ#modsopsplayers-keep-having-their-game-mode-switched
* https://github.com/Multiverse/Multiverse-Core/wiki/Big-List-O-Permissions#access-permissions
https://github.com/Multiverse/Multiverse-Core/blob/bebd4742b95c300718e0b9bfa82cc8383f6ba82a/src/main/java/com/onarandombox/MultiverseCore/MVWorld.java#L389

**Comment by leasoncre** [comment] 2016-03-11 18:37
I have looked into this. and it doesn't work (tested in 1.9).
I don't have this issue in 1.8.8 if i'm opped. non-opped players need the node. (as expected)

**Comment by FernFerret** [comment] 2016-03-12 17:33
- [ ] What permission plugin are you using if any?
- [ ] Can you give me some [simple steps to reproduce](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug#simple-steps-to-reproduce)?

**Comment by leasoncre** [comment] 2016-03-13 02:47
group manager atm, but that's gotta change soon, it's bugged in 1.9 and not updated anymore. testing everything i can on 1.9 private dev server before upgrading the live server.
[[dreading the update to new perms plugin, recommendations?]]

since you asked what perms plugin, and i have GM atm, i assume it's the cause. HOWEVER, i have verified this without GM installed (or any perms plugin)
-- installed plugins/server ver: --
git-Spigot-6f291ea-55a8535 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
Multiverse-Core version 2.5-b717
Multiverse-NetherPortals version 2.5-b708
-- steps: --
load only multiverse and multiverse-netherportals (latest dev versions)
log into server (as opped player)
/gamemode 1
walk through a nether portal
find myself in gm 0

```
[21:40:06] [Server thread/INFO]: leasoncre issued server command: /mv version -p
[21:40:06] [Server thread/INFO]: [Multiverse-Core] [Multiverse-Core] Multiverse-Core Version: 2.5-b717
[21:40:06] [Server thread/INFO]: [Multiverse-Core] [Multiverse-Core] Bukkit Version: git-Spigot-6f291ea-55a8535 (MC: 1.9)
[21:40:06] [Server thread/INFO]: [Multiverse-Core] [Multiverse-Core] Loaded Worlds: [{"MVWorld@1421973092":{"Gen":"null","Type":"NORMAL","Env":"THE_END","Name":"world_the_end"}}, {"MVWorld@1400296843":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world"}}, {"MVWorld@1520398529":{"Gen":"null","Type":"NORMAL","Env":"NETHER","Name":"world_nether"}}]
[21:40:06] [Server thread/INFO]: [Multiverse-Core] [Multiverse-Core] Multiverse Plugins Loaded: 1
[21:40:06] [Server thread/INFO]: [Multiverse-Core] [Multiverse-Core] Economy being used: Essentials Economy
[21:40:06] [Server thread/INFO]: [Multiverse-Core] [Multiverse-Core] Permissions Plugin: Bukkit Permissions (SuperPerms)
[21:40:06] [Server thread/INFO]: [Multiverse-Core] [Multiverse-Core] Dumping Config Values: (version 2.9)
[21:40:06] [Server thread/INFO]: [Multiverse-Core] [Multiverse-Core]  messagecooldown: 5000
[21:40:06] [Server thread/INFO]: [Multiverse-Core] [Multiverse-Core]  teleportcooldown: 1000
[21:40:06] [Server thread/INFO]: [Multiverse-Core] [Multiverse-Core]  worldnameprefix: false
[21:40:06] [Server thread/INFO]: [Multiverse-Core] [Multiverse-Core]  worldnameprefixFormat: [%world%]%chat%
[21:40:06] [Server thread/INFO]: [Multiverse-Core] [Multiverse-Core]  enforceaccess: false
[21:40:06] [Server thread/INFO]: [Multiverse-Core] [Multiverse-Core]  displaypermerrors: true
[21:40:06] [Server thread/INFO]: [Multiverse-Core] [Multiverse-Core]  teleportintercept: false
[21:40:06] [Server thread/INFO]: [Multiverse-Core] [Multiverse-Core]  firstspawnoverride: true
[21:40:06] [Server thread/INFO]: [Multiverse-Core] [Multiverse-Core]  firstspawnworld: world
[21:40:06] [Server thread/INFO]: [Multiverse-Core] [Multiverse-Core]  debug: 0
[21:40:06] [Server thread/INFO]: [Multiverse-Core] [Multiverse-Core] Special Code: FRN002
[21:40:06] [Server thread/INFO]: [Multiverse-Core] [Multiverse-NetherPortals] Multiverse-NetherPortals Version: 2.5-b708
[21:40:06] [Server thread/INFO]: [Multiverse-Core] [Multiverse-NetherPortals] World links: {}
[21:40:06] [Server thread/INFO]: [Multiverse-Core] [Multiverse-NetherPortals] Nether Prefix: 
[21:40:06] [Server thread/INFO]: [Multiverse-Core] [Multiverse-NetherPortals] Nether Suffix: _nether
[21:40:06] [Server thread/INFO]: [Multiverse-Core] [Multiverse-NetherPortals] Special Code: FRN001
[21:40:08] [Craft Scheduler Thread - 4/INFO]: com.onarandombox.MultiverseCore.utils.webpaste.PasteFailedException: java.io.IOException: Server returned HTTP response code: 503 for URL: http://pastie.org/private/ofvv6hj4497kfkfcmyfa
[21:40:08] [Craft Scheduler Thread - 4/INFO]: [Multiverse-Core] Version info dumped here: Error posting to service
```

**Comment by leasoncre** [comment] 2016-03-16 10:33
with only PermissionsEX and Multiverse/Multiverse-NetherPortals installed this is not an issue

without ANY permissions plugin this IS an issue

[group-manager sucks]

**Comment by FernFerret** [comment] 2016-03-17 00:37
I use PermissionsBukkit in testing. I'm typing up a longer reply (and was almost done) but a thing happened that I'm investigating...

**Comment by leasoncre** [comment] 2016-03-17 00:40
yeah. it's a weird one. i added all my plugins back for testing (about 50 of them) with pex, and it wouldn't change my gamemode, then i went to the end.. and bam survival.. like.. it seems to be an inconsistent bug. hope ya find it!

**Comment by FernFerret** [comment] 2016-03-17 01:18
Ok, it appears as if it _fails_ the **first time** a server is loaded with Multiverse properly, but not after that. Not sure if it's a spigot problem or ours, still investigating...

**Comment by MomaCods** [comment] 2016-03-26 23:19
So Multiverse is working in 1.9? I use PermissionsEx should I be ok?

**Comment by leasoncre** [comment] 2016-03-27 01:28
@MomaCods yeah, i use the latest dev build (on my test server) and pex, works fine. aside from this issue that i'm having

**Comment by FernFerret** [comment] 2016-04-13 22:30
@leasoncre If the issue remains open that just means sadly I haven't had time to look at it yet, but I was able to reproduce this. I'm going to try newer spigot builds.

Were you able to reproduce it after the initial server load?

**Comment by Feerko** [comment] 2016-04-26 19:35
I have the same problem. I use bungeeperms.

[21:35:14 INFO]: [Multiverse-Core] [Multiverse-Core] Multiverse-Core Version: 2.5-b719
[21:35:14 INFO]: [Multiverse-Core] [Multiverse-Core] Bukkit Version: git-Spigot-e6f93f4-935f18b (MC: 1.9.2)
[21:35:14 INFO]: [Multiverse-Core] [Multiverse-Core] Loaded Worlds: [{"MVWorld@1865837926":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"lobby"}}, {"MVWorld@2006805763":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"arena"}}]
[21:35:14 INFO]: [Multiverse-Core] [Multiverse-Core] Multiverse Plugins Loaded: 0
[21:35:14 INFO]: [Multiverse-Core] [Multiverse-Core] Economy being used: Simple Item Economy
[21:35:14 INFO]: [Multiverse-Core] [Multiverse-Core] Permissions Plugin: Bukkit Permissions (SuperPerms)
[21:35:14 INFO]: [Multiverse-Core] [Multiverse-Core] Dumping Config Values: (version 2.9)
[21:35:14 INFO]: [Multiverse-Core] [Multiverse-Core]  messagecooldown: 5000
[21:35:14 INFO]: [Multiverse-Core] [Multiverse-Core]  teleportcooldown: 1000
[21:35:14 INFO]: [Multiverse-Core] [Multiverse-Core]  worldnameprefix: false
[21:35:14 INFO]: [Multiverse-Core] [Multiverse-Core]  worldnameprefixFormat: [%world%]%chat%
[21:35:14 INFO]: [Multiverse-Core] [Multiverse-Core]  enforceaccess: false
[21:35:14 INFO]: [Multiverse-Core] [Multiverse-Core]  displaypermerrors: true
[21:35:14 INFO]: [Multiverse-Core] [Multiverse-Core]  teleportintercept: true
[21:35:14 INFO]: [Multiverse-Core] [Multiverse-Core]  firstspawnoverride: true
[21:35:14 INFO]: [Multiverse-Core] [Multiverse-Core]  firstspawnworld: lobby
[21:35:14 INFO]: [Multiverse-Core] [Multiverse-Core]  debug: 0
[21:35:14 INFO]: [Multiverse-Core] [Multiverse-Core] Special Code: FRN002

**Comment by dumptruckman** [comment] 2016-04-28 16:55
So... I am not seeing this issue on my own server using Group Manager. I want to get this resolved though because it is time to release 2.5 so that we can stop people from using 2.4.

**Comment by dumptruckman** [comment] 2016-04-28 16:56
@FernFerret Hate to say it but without more dev activity the the AB concept is going away and we're moving to plain ol' releases.

**Comment by FernFerret** [comment] 2016-04-28 18:26
Oh totally. Let's do it. Let's release 2.5.0. I'm on board. This worked for
me back in the 2.0-2.3 because I was doing tons of work.

We're a lot more stable now than we were back then!

**Comment by dumptruckman** [comment] 2016-04-28 20:58
Cool, I will see about working on this next week. This week is a bit
crammed due to finals and such. I think 2.5.0 is a good idea and snapshots
between versions.

**Comment by ScuroK** [comment] 2016-08-18 10:48
I have the same problem! can you fix this please?

**Closed** 2019-06-06 01:53 UTC
Labels: Assistance, Bug
