### ISSUE TITLE
Exception while loading value for environment?

### ISSUE THREAD

**Issue by iornminer** [Multiverse/Multiverse-Core#2344] opened 2020-07-13 17:16 UTC
So basically, my server doesn't want to load multiverse, these are the errors. Note: I uninstalled every plugin and added multiverse, didn't work. PLEASE PLEASE help:
[19:08:24] [Server thread/WARN]: [Multiverse-Core] Exception while loading value for environment <--- said this a bunch of times
[19:08:24] [Server thread/ERROR]: Error occurred while enabling Multiverse-Core v4.1.0-b775 (Is it up to date?)
java.lang.IllegalArgumentException: Cannot set to an empty path
at org.apache.commons.lang.Validate.notEmpty(Validate.java:321) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.configuration.MemorySection.set(MemorySection.java:188) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.configuration.MemorySection.set(MemorySection.java:222) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.configuration.file.YamlConfiguration.convertMapsToSections(YamlConfiguration.java:79) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.configuration.file.YamlConfiguration.convertMapsToSections(YamlConfiguration.java:77) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:67) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:183) ~[patched_1.15.2.jar:git-Paper-214]
at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorldConfig(WorldManager.java:775) ~[?:?]
at com.onarandombox.MultiverseCore.MultiverseCore.loadConfigs(MultiverseCore.java:504) ~[?:?]
at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:306) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-214]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-214]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-214]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:895) ~[patched_1.15.2.jar:git-Paper-214]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[19:08:24] [Server thread/INFO]: [Multiverse-Core] Disabling Multiverse-Core v4.1.0-b775
[19:08:24] [Server thread/ERROR]: Error occurred while disabling Multiverse-Core v4.1.0-b775 (Is it up to date?)
java.lang.NullPointerException: null
at com.onarandombox.MultiverseCore.utils.WorldManager.saveWorldsConfig(WorldManager.java:822) ~[?:?]
at com.onarandombox.MultiverseCore.MultiverseCore.saveWorldConfig(MultiverseCore.java:1155) ~[?:?]
at com.onarandombox.MultiverseCore.MultiverseCore.saveMVConfigs(MultiverseCore.java:1163) ~[?:?]
at com.onarandombox.MultiverseCore.MultiverseCore.onDisable(MultiverseCore.java:873) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-214]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-214]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-214]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:895) ~[patched_1.15.2.jar:git-Paper-214]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by nicegamer7** [comment] 2020-09-21 02:10
I'm going to close this as a duplicate of #2269.

**Closed by nicegamer7** 2020-09-21 02:10 UTC
