### ISSUE TITLE
Multiverse suddenly broke

### ISSUE THREAD

**Issue by Awesomeguys900** [Multiverse/Multiverse-Core#2596] opened 2021-03-10 09:20 UTC
### Information

* **Server version:**  
![gere](https://user-images.githubusercontent.com/45321733/110603733-6d822a00-81db-11eb-9a30-76da4f3c3183.PNG)

* **Full output of `/mv version -p`:**  https://paste.gg/p/anonymous/58733f42550d4091a5cfc55a2642e793

* **Server log:**  https://gist.github.com/Awesomeguys900/35951276328669c4138a820401b49f18

### Help request

**Problem**
 My Multiverse randomly crashed and doesnt load, when I do a command it says interval server error 

**What I have tried**
 Updating versions

**Screenshots**

**Comment by benwoo1110** [comment] 2021-03-10 09:23
https://github.com/PaperMC/Paper/issues/5331 This is an issue with paper and having faulty logic for invalid world name validation.

Update paper at: https://papermc.io/downloads 

I will leave this issue open for awhile so ppl know to update papermc. This is NOT a bug with mutliverse.

**Comment by Dnaleor77** [comment] 2021-03-11 11:50
Problem persist on paper-545 of march 10...

**Comment by benwoo1110** [comment] 2021-03-11 11:51
> Problem persist on paper-545 of march 10...

1. Ensure you actually, updated, sometime server host does weird things
2. Your world names cannot have space or other special charaters

**Comment by Dnaleor77** [comment] 2021-03-11 23:38
Unfortunately, I am sure it's updated. The server is running on a private server at home. No hosting involved.

Problem I am facing; the first world had all playerdata and has spaces in the world-name. If I change it - and edit config files accordingly - players lose all stats and so on...

Why wasn't this an issue before all this...?

**Comment by Awesomeguys900** [comment] 2021-03-12 00:37
If you download the new Paper Version, It should fix it, it worked for me

**Comment by benwoo1110** [comment] 2021-03-12 03:42
@Dnaleor77 In 1.15, there was a change that disallow loading of worlds with spaces, but for some reason they didn't do this check for the default world and now its finally implemented. So if your default `level-name` world had space, it will be an issue. You will have to adjust accordingly and contact paper if the world continues to not load properly.

**Comment by Dnaleor77** [comment] 2021-03-12 10:10
It works now, thank you. It was the default world with the spaces in them like @benwoo1110 suggested. Renaming the world directory and names in the config-files did the job.
'
@benwoo1110 thank you for clarifying! the playerdata loss was simply because I renamed everything, except the world-name in the server.properties, which caused the server to actually generate a new world with spaces in the name

**Comment by benwoo1110** [comment] 2021-04-27 15:29
This should be fixed quite some time ago by papermc. As such, closing the issue.

**Closed by benwoo1110** 2021-04-27 15:29 UTC
Labels: Bug: Confirmed, Resolution: Unrelated to MV
