### ISSUE TITLE
Property values reset on server reload

### ISSUE THREAD

**Issue by Vaporizer8** [Multiverse/Multiverse-Core#1019] opened 2012-12-26 16:02 UTC
I'm having issues with some property values getting reset.
Might be related to #986 and #982 altough the pvp and keepSpawnInMemory values have not caused any problems for me. I only managed to break the following three:

The difficulty value resets to the value in server.properties for all worlds on reload.
Steps to reproduce:
- Set up a clean server with just Bukkit and Multiverse-Core (I used Bukkit rev2573 and Multiverse-Core rev651).
- Start the server and let it generate worlds.yml.
- Type "mvm set difficulty hard world" and open worlds.yml to check that the difficulty for "world" is set to hard.
- Stop and start the server. The difficulty in worlds.yml should still be set to hard.
- Type "reload" (not "mv reload").
- Open worlds.yml and see that the difficulty is reverted to easy (or whatever you've set the difficulty to in server.properties).

The seed value reverts to whatever is in the level.dat on reload, mv reload and stop/start.
Steps to reproduce:
- Set up a clean server with just Bukkit and Multiverse-Core (I used Bukkit rev2573 and Multiverse-Core rev651).
- Start the server and let it generate worlds.yml.
- Type "mvm set seed 1234 world" and open worlds.yml to check that the seed for "world" is set to 1234.
- Stop/start the server or type "reload" or "mv reload".
- The seed in worlds.yml is now the original value from level.dat.

The environment value reverts to the default value for the world in server.properties (and its nether/end) on reload, mv reload and stop/start.
Steps to reproduce:
- Set up a clean server with just Bukkit and Multiverse-Core (I used Bukkit rev2573 and Multiverse-Core rev651).
- Start the server and let it generate worlds.yml.
- Type "mvm set environment NETHER world" and open worlds.yml to check that the environment for "world" is set to NETHER.
- Stop/start the server or type "reload" or "mv reload".
- The environment in worlds.yml is now the original value.
- This is only the case for the default worlds, world, world_nether and world_the_end (or whatever you've set the level-name to in server.properties).

**Comment by frankwalter1301** [comment] 2020-07-27 22:45
> 
> 
> Please let me know if this build fixes the issue http://ci.onarandombox.com/job/Multiverse-Core/687/

I saw people commenting with this problem on build hosted by bukkit plugin website. It has a 2019 build.

**Comment by benwoo1110** [comment] 2020-10-12 08:16
Duplicate of #778

**Closed by benwoo1110** 2020-10-12 08:16 UTC
Labels: Type: Bug
