### ISSUE TITLE
Errors starting MVC in 1.15.2 server

### ISSUE THREAD

**Issue by ZubeySweet** [Multiverse/Multiverse-Core#2285] opened 2020-06-12 05:51 UTC
>.... [05:45:40 INFO]: [Multiverse-Core] 5 - World(s) loaded.
>.... [05:45:40 ERROR]: Error occurred while enabling Multiverse-Core v4.1.0-b775 (Is it up to date?)
java.lang.NullPointerException: null
at com.onarandombox.buscript.ScriptManager.<init>(ScriptManager.java:31) ~[?:?]
at com.onarandombox.buscript.Buscript.<init>(Buscript.java:77) ~[?:?]
at com.onarandombox.buscript.Buscript.<init>(Buscript.java:65) ~[?:?]
at com.onarandombox.MultiverseCore.MultiverseCore.initializeBuscript(MultiverseCore.java:351) ~[?:?]
at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:337) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-349]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-349]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-349]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-349]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-349]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-349]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-349]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-349]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
>.... [05:45:40 INFO]: [Multiverse-Core] Disabling Multiverse-Core v4.1.0-b775

**Comment by nicegamer7** [comment] 2020-06-12 06:01
I'm going to close this as a duplicate of #2215.

There's a build of MV there with a temporary fix. Also please send a list of your plugins there to help us diagnose what causes it.

**Closed** 2020-06-12 06:01 UTC
Labels: Duplicate
