### ISSUE TITLE
PVP Overriding

### ISSUE THREAD

**Issue by JordyPin** [Multiverse/Multiverse-Core#1969] opened 2019-02-15 15:13 UTC
For a couple months, I've been having issues with PVP on my server. Having narrowed down the issue, I've enabled pvp in server.properties, in worldguard, and in multiverse. However, even with worldguard flags, Multiverse is overriding it and is allowing pvp. Is there a way to stop multiverse from overriding? 

I've tried it in different worlds, but if I have multiverse pvp set to true, it allows pvp even with worldguard having it denied. If I have multiverse pvp set to false, and worldguard set to true, it still doesn't allow for pvp.

It's a 1.12.2 server running multiverse version 2.6.0-b738

**Comment by Jadiction** [comment] 2019-06-03 08:41
Duplicate of https://github.com/Multiverse/Multiverse-Core/issues/1798

**Closed by Jadiction** 2019-06-03 08:41 UTC
Labels: Duplicate
