### ISSUE TITLE
Multiverse Nether Portal Error

### ISSUE THREAD

**Issue by TheKingMarian** [Multiverse/Multiverse-Core#1995] opened 2019-05-11 10:13 UTC
When someone tryes to enter the nether portal in console apears this

[ERROR] Could not pass event PlayerPortalEvent to Multiverse-Core v3.0.0-SNAPSHOT-b760

org.bukkit.event.EventException: null

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.PlayerList.changeDimension(PlayerList.java:765) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.EntityPlayer.b(EntityPlayer.java:627) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.Entity.postTick(Entity.java:346) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1632) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.World.h(World.java:1601) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.WorldServer.l(WorldServer.java:691) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1403) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:668) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

Caused by: java.lang.NoSuchFieldError: org/bukkit/Material.NETHER_PORTAL

at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerPortalCheck(MVPlayerListener.java:255) ~[?:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

... 16 more

**Comment by kaniesha** [comment] 2019-05-30 19:03
Having the same issue. Server is running spigot 1.14.2. Users are entering nether portals, crashing out of the game with an internal service error, and then logging back into the end.

https://gist.github.com/kaniesha/e2181664a7cf8865e1c934360e7b6930

**Comment by Jadiction** [comment] 2019-06-03 10:10
Please read my comment on #1998 Ticket closed. Duplicate of https://github.com/Multiverse/Multiverse-Core/issues/1998

**Closed by Jadiction** 2019-06-03 10:10 UTC
Labels: Duplicate
