### ISSUE TITLE
[Bug]: when i execute "mv gens" console says error

### ISSUE THREAD

**Issue by iKunX** [Multiverse/Multiverse-Core#2813] opened 2022-11-18 23:12 UTC
### `/mv version -p` output

[18:11:00 INFO]: [Multiverse-Core] Version info dumped here: https://paste.gg/54ca3b47702e4ad99550b42f9f441763

### Server logs

https://mclo.gs/xQswEy0

### Server Version

```shell
1.16.5
```

### Bug Description

When running /mv gens it send an error

### Steps to reproduce

1. Create a PaperMC server in 1.16.5
2. Add Terra Plugin
3. Execute the server
4. Run /mc gens

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by benwoo1110** [comment] 2022-12-31 09:32
Duplicate of #2811

**Closed by benwoo1110** 2022-12-31 09:32 UTC
Labels: Bug: Unconfirmed

**Comment by Faustyu1** [comment] 2023-02-05 13:03
UP
