### ISSUE TITLE
Depreciated event Error in logs

### ISSUE THREAD

**Issue by brobie1kanobi** [Multiverse/Multiverse-Core#2077] opened 2019-08-18 03:49 UTC
When starting my server this error comes up in my logs. It tells me to report it, so I am. 

![image](https://user-images.githubusercontent.com/45983894/63219875-86cf0b80-c149-11e9-80d4-2a1e30dcf06a.png)

I am new to this so I may not be doing this right, any help will be appreciated.

**Comment by ljacqu** [comment] 2019-08-18 07:16
Duplicate of #2000

**Comment by bryangs18** [comment] 2019-08-18 23:41
I have the same problem

**Comment by brobie1kanobi** [comment] 2019-08-19 08:33
> Duplicate of #2000

Thank you @ljacqu

**Closed** 2019-08-19 08:33 UTC
