### ISSUE TITLE
Weird Nullpointer Exception

### ISSUE THREAD

**Issue by JavaFactoryDev** [Multiverse/Multiverse-Core#2352] opened 2020-07-17 16:47 UTC
[21:50:40] [Server thread/ERROR]: Error occurred while enabling Multiverse-Core v4.1.1-SNAPSHOT-b777 (Is it up to date?)
java.lang.NullPointerException: null
    at com.onarandombox.buscript.ScriptManager.<init>(ScriptManager.java:31) ~[?:?]
    at com.onarandombox.buscript.Buscript.<init>(Buscript.java:77) ~[?:?]
    at com.onarandombox.buscript.Buscript.<init>(Buscript.java:65) ~[?:?]
    at com.onarandombox.MultiverseCore.MultiverseCore.initializeBuscript(MultiverseCore.java:353) ~[?:?]
    at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:337) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-378]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-378]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-378]
    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-378]
    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-378]
    at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-378]
    at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-378]
    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-378]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[21:50:40] [Server thread/INFO]: [Multiverse-Core] Disabling Multiverse-Core v4.1.1-SNAPSHOT-b777

**Comment by nicegamer7** [comment] 2020-07-17 19:01
I'm closing this as a duplicate of #2215. There's a build in that issues that that works around this issue.

**Closed by nicegamer7** 2020-07-17 19:01 UTC
