### ISSUE TITLE
[Bug]: Error / Warn on startup Paper 1.20.1 Build 22

### ISSUE THREAD

**Issue by Tsoccerguy3** [Multiverse/Multiverse-Core#2925] opened 2023-06-15 22:06 UTC
### `/mv version -p` output

https://paste.gg/p/anonymous/88f4073995cb45668e3ab7af018cee52

### Server logs

https://paste.gg/p/anonymous/ba3e324344994359857cf187e00565a7

### Server Version

```shell
[23:47:43 INFO]: This server is running Paper version git-Paper-22 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: f7b386d)
You are running the latest version
Previous version: git-Paper-20 (MC: 1.20.1)
```

### Bug Description

Warn on startup when Paper 1.20.1 Build 22 first loads Multiverse-core . Tested with no plugins , NO ERRORS . Tested with all plugins Error / Warn . Tested with just Multiverse-core , Error / Warn . 

Problem with Paper 1.20.1 Build 22 . Does not effect the server as far as I can tell , but I think you should update dependencies , etc ...

### Steps to reproduce

Just update to Paper 1.20.1 Build 22
only add multiverse-core-4.3.9.jar to plugins to trigger error / warn 
[latest.log](https://github.com/Multiverse/Multiverse-Core/files/11763631/latest.log)

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by NeverGrowUp** [comment] 2023-06-15 22:25
Did you read the next line after the warning? Line 97...

**Comment by Tsoccerguy3** [comment] 2023-06-16 00:14
> Did you read the next line after the warning? Line 97...

Yes Those few line have been there for many versions , Im aware of it

The new warning , that starts at the very top after paper loads , is related to 1.20.1 and related to a server running in a Docker image on a Host . This started after we switched from 1.19.4 . If I remove Multiverse then this does not happen . Multiverse needs a update

**Comment by Tsoccerguy3** [comment] 2023-06-16 00:16
Here is the link to paper issue https://github.com/PaperMC/Paper/issues/9352#issue-1759378331 . They closed it as not a Paper problem

**Comment by NeverGrowUp** [comment] 2023-06-16 00:36
Can you show logs without multiverse? Are you running this server behind a proxy?
This is occuring before multiverse is loaded.

**Comment by Tsoccerguy3** [comment] 2023-06-16 04:11
The server is running on Fragnet Hosting service on a VM Docker Image and Yes it would use some kind of Proxy. I am guessing a Hosting company would have 100's of clients on a node each in a Docker Image and each VM runs like a localhost . This is just a warning , the server does work . I will revisit the issue at a later date when more bugs are worked out in 1.20.1 . It may be a Mojang bug . 

The order of things
Docker Boot sets enviroment
Loads Paper with all its settings
Network testing , Microsoft authentication
Plugin Manager figures out order to load plugins
Warn happens at this point .

Tested fine on my home computer server on local host .

**Comment by HenrikoMagnifico** [comment] 2023-06-24 13:49
Having the same issue

**Comment by zax71** [comment] 2023-06-24 15:56
I cannot reproduce this in a standard test environment. If someone could recreate the exact docker setup required, then I'd be happy to test again

**Comment by Tsoccerguy3** [comment] 2023-06-25 15:10
For security reasons , a client would not have access to a hosting companies Docker Image . I did mention this in other Gits . Paper was able to fix this in latest builds

**Comment by zax71** [comment] 2023-06-25 15:11
Ah, can I close this issue now?

**Closed** 2023-08-19 03:37 UTC
Labels: Bug: Can't Reproduce, Type: Upstream
