### ISSUE TITLE
mv-core

### ISSUE THREAD

**Issue by s7an1slaw** [Multiverse/Multiverse-Core#2322] opened 2020-06-30 22:49 UTC
[01:47:38 WARN]: [Multiverse-Core] "Multiverse-Core v4.1.0-b775" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

**Comment by nicegamer7** [comment] 2020-07-01 09:41
This message is nothing to worry about, see the message right below it! Closing this as a duplicate of #2000.

**Closed by nicegamer7** 2020-07-01 09:41 UTC
