### ISSUE TITLE
Denying animal natural spawn, while allowing egg-spawn

### ISSUE THREAD

**Issue by Shiikii** [Multiverse/Multiverse-Core#1881] opened 2017-12-24 14:25 UTC
Hi!

I wanted on my server to DENY natural spawn of animals (Pigs, chickens, horses, etc), while allowing spawning them from EGGS & breeding them. I found similar issue from 2012 - https://github.com/Multiverse/Multiverse-Core/issues/692

But it seems something change in MV-Core / Minecraft itself and I'm unable to use that solution:
```
exceptions: 
        - MONSTER_EGG
        - SPAWNER_EGG
```

So my question here is: Can I DENY natural spawn and ALLOW egg-spawn of animals? What should I type in world.yml to make it?

Thank you in advance!

**Comment by Jadiction** [comment] 2019-06-04 00:29
Duplicate of https://github.com/Multiverse/Multiverse-Core/issues/790 (Just with animals and not monsters)

**Closed by Jadiction** 2019-06-04 00:29 UTC
Labels: Duplicate
