### ISSUE TITLE
listener for org.bukkit.event.entity.EntityCreatePortalEvent

### ISSUE THREAD

**Issue by zBoringDrop** [Multiverse/Multiverse-Core#2049] opened 2019-07-24 19:03 UTC
Multiverse core show this error on startup of my paperspigot 1.14.4 server: https://pastebin.com/KA384i2Y

**Comment by dumptruckman** [comment] 2019-07-25 12:59
Duplicate of #2000.

**Closed by dumptruckman** 2019-07-25 12:59 UTC
