### ISSUE TITLE
[Bug]: It needs to enter /mv confirm to enter

### ISSUE THREAD

**Issue by bananaQwQ666** [Multiverse/Multiverse-Core#2869] opened 2023-02-25 12:50 UTC
### `/mv version -p` output

[20:44:57 INFO]: [Multiverse-Core] Multiverse-Core Version: 4.3.0-b846 [20:44:57 INFO]: [Multiverse-Core] Bukkit Version: git-Paper-387 (MC: 1.18.2) [20:44:57 INFO]: [Multiverse-Core] Loaded Worlds: [{"MVWorld@1862120694":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"zsj"}}, {"MVWorld@1108694254":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"spawn"}}, {"MVWorld@613117509":{"Gen":"null","Type":"FLAT","Env":"THE_END","Name":"spawn_the_end"}}, {"MVWorld@1064077964":{"Gen":"PlotSquared","Type":"NORMAL","Env":"NORMAL","Name":"plot"}}, {"MVWorld@1010160531":{"Gen":"null","Type":"FLAT","Env":"NETHER","Name":"spawn_nether"}}, {"MVWorld@1416577759":{"Gen":"PlotSquared","Type":"NORMAL","Env":"NORMAL","Name":"plots"}}] [20:44:57 INFO]: [Multiverse-Core] Multiverse Plugins Loaded: 0 [20:44:57 INFO]: [Multiverse-Core] Economy being used: CMIEconomy [20:44:57 INFO]: [Multiverse-Core] Permissions Plugin: Bukkit Permissions (SuperPerms) [20:44:57 INFO]: [Multiverse-Core] Dumping Config Values: (version 2.9) [20:44:57 INFO]: [Multiverse-Core]   enforceaccess: false [20:44:57 INFO]: [Multiverse-Core]   prefixchat: false [20:44:57 INFO]: [Multiverse-Core]   prefixchatformat: [%world%]%chat% [20:44:57 INFO]: [Multiverse-Core]   useasyncchat: true [20:44:57 INFO]: [Multiverse-Core]   teleportintercept: true [20:44:57 INFO]: [Multiverse-Core]   firstspawnoverride: true [20:44:57 INFO]: [Multiverse-Core]   displaypermerrors: true [20:44:57 INFO]: [Multiverse-Core]   enablebuscript: true [20:44:57 INFO]: [Multiverse-Core]   globaldebug: 0 [20:44:57 INFO]: [Multiverse-Core]   silentstart: false [20:44:57 INFO]: [Multiverse-Core]   messagecooldown: 5000 [20:44:57 INFO]: [Multiverse-Core]   version: 2.9 [20:44:57 INFO]: [Multiverse-Core]   firstspawnworld: spawn [20:44:57 INFO]: [Multiverse-Core]   teleportcooldown: 1000 [20:44:57 INFO]: [Multiverse-Core]   defaultportalsearch: false [20:44:57 INFO]: [Multiverse-Core]   portalsearchradius: 128 [20:44:57 INFO]: [Multiverse-Core]   autopurge: true [20:44:57 INFO]: [Multiverse-Core] Special Code: FRN002

### Server logs

https://paste.gg/p/anonymous/715a7b3f22884464a7a67e8c06ee59e1

### Server Version

```shell
[20:46:26 INFO]: --------------------------------------------------
[20:46:26 INFO]: CMI 插件版本: 9.2.3.0 SqLite-> 9.3.1.5
[20:46:26 INFO]: CMILib: 1.2.4.5
[20:46:26 INFO]: 服务器版本: Paper(387) 1.18.2-R0.1-SNAPSHOT
[20:46:26 INFO]: CMI 经济: 启用 经济: 1.7.3-b131(CMIEInjector) CMI 聊天: 禁用
[20:46:26 INFO]: 模块 -> 52 已启用 4 已禁用: tablist, ranks, votifier, kits
[20:46:26 INFO]: --------------------------------------------------
```

### Bug Description

When I enter /mvtp {world}, it prompts "Multiverse did not teleport you to {world} because it was unsafe.Would you like to try anyway?" and asks me to enter /mv confirm to enter the world, so it becomes Very troublesome, is there any solution?

### Steps to reproduce

1. Enter /mvtp{world}
2. The plug-in prompts "world unsafe" and requires input /mvconfirm to enter the world

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by Lildirt** [comment] 2023-02-27 17:21
`/mvconfirm` is intended to exist, and the confirmation that you're seeing is expected for worlds with an unsafe spawn.
This is not a bug.

A feature request has been opened [here](https://github.com/Multiverse/Multiverse-Core/issues/2764) that will let you bypass the confirm option and is roadmapped to be implemented with MV5.

**Comment by zax71** [comment] 2023-03-02 12:07
Closing, as this is currently a non-issue and the new feature should be tracked in #2764

**Closed by zax71** 2023-03-02 12:07 UTC
Labels: Bug: Unconfirmed
