### ISSUE TITLE
[Multiverse-Core]

### ISSUE THREAD

**Issue by XiaoWen12** [Multiverse/Multiverse-Core#2056] opened 2019-07-31 21:45 UTC
How to solve this problem?

> [21:24:25] [Server thread/WARN]: [Multiverse-Core] "Multiverse-Core v4.0.0-b766" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

**Comment by dumptruckman** [comment] 2019-08-01 04:12
It's not a problem besides this being a duplicate of #2000

**Closed by dumptruckman** 2019-08-01 04:12 UTC
