### ISSUE TITLE
[Bug]: Please let the author know

### ISSUE THREAD

**Issue by JIMIN0402** [Multiverse/Multiverse-Core#3059] opened 2024-03-02 14:45 UTC
### `/mv version -p` output

https://paste.gg/p/anonymous/59d61ab4192f4eae9a3d77d50df1a83a

### Server logs

not error

### Server Version

```shell
This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
```

### Bug Description

[23:40:00 INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.3.12
[23:40:00 WARN]: [Multiverse-Core] "Multiverse-Core v4.3.12" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].
[23:40:00 INFO]: [Multiverse-Core] §aWe are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.
[23:40:00 INFO]: [Multiverse-Core] 3 - World(s) loaded.
[23:40:00 WARN]: [Multiverse-Core] Buscript failed to load! The script command will be disabled! If you would like not to see this message, use `/mv conf enablebuscript false` to disable Buscript from loading.
[23:40:00 INFO]: [Multiverse-Core] Version 4.3.12 (API v24) Enabled - By dumptruckman, Rigby, fernferret, lithium3141 and main--

### Steps to reproduce

[23:40:00 INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.3.12
[23:40:00 WARN]: [Multiverse-Core] "Multiverse-Core v4.3.12" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].
[23:40:00 INFO]: [Multiverse-Core] §aWe are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.
[23:40:00 INFO]: [Multiverse-Core] 3 - World(s) loaded.
[23:40:00 WARN]: [Multiverse-Core] Buscript failed to load! The script command will be disabled! If you would like not to see this message, use `/mv conf enablebuscript false` to disable Buscript from loading.
[23:40:00 INFO]: [Multiverse-Core] Version 4.3.12 (API v24) Enabled - By dumptruckman, Rigby, fernferret, lithium3141 and main--

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by NeverGrowUp** [comment] 2024-03-02 22:11
The 3rd line answers it..
`[23:40:00 INFO]: [Multiverse-Core] §aWe are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.`

**Comment by zax71** [comment] 2024-03-02 22:34
Duplicate of #2000

**Closed by zax71** 2024-03-02 22:35 UTC
Labels: Bug: Unconfirmed
