### ISSUE TITLE
how do i make world specific command blocks

### ISSUE THREAD

**Issue by sexibatka** [Multiverse/Multiverse-Core#2552] opened 2021-02-01 07:24 UTC
### Information

* **Server version:** Paper 1.16.5 R0.1 Snapshot 

* **Full output of `/mv version -p`:**https://paste.gg/p/anonymous/9071b123746242c2bba0b9e703f9f3f5 

* **Server log:**https://gist.github.com/sexibatka/e6aaa63cf2053cf620963a941132325e  

### Help request

**Problem**
I am trying to figure out how to make command blocks world specific 

**What I have tried**
nothing 

**Screenshots**

**Comment by willkroboth** [comment] 2021-02-13 18:21
To only target entities in a specific world, you can use their WorldUUIDMost in a command like this:
/tell @e[nbt={WorldUUIDMost:[WorldUUIDMost]} hello
 where you replace [WorldUUIDMost] with that world's UUIDMost. To find a world's UUIDMost, go to that world and run the command: 
/data get entity @s WorldUUIDMost
This will return a number into the chat like:
25678193678189L
Just use this value (including the L at the end) to replace [WorldUUIDMost], and the command should only affect entities in the world you want. If any part of this doesn't work for you or you need help understanding, don't hesitate to ask.

**Comment by benwoo1110** [comment] 2021-02-16 03:41
As of now and probably for the near future, mv won't touch how command block works. I will mark it duplicate of #1983

**Closed by benwoo1110** 2021-02-16 03:41 UTC
Labels: Resolution: Duplicate, Type: Assistance
