### ISSUE TITLE
Cannot delete world

### ISSUE THREAD

**Issue by PappoYT** [Multiverse/Multiverse-Core#2648] opened 2021-06-22 12:04 UTC
### Information

* **Server version:** 
This server is running Paper version git-Paper-772 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 6 version(s) behind
Previous version: git-Paper-753 (MC: 1.16.5)

* **Full output of `/mv version -p`:** 
[https://pastebin.com/2E0HCt7n](https://pastebin.com/2E0HCt7n)

* **Server log:**
[https://mclo.gs/SVuxlXg](https://mclo.gs/SVuxlXg)

### Details

**Description**  
I want to permanently delete a world with `/mv delete` command but after restart the server the world is back again.

**Steps to reproduce**  
I want to permanently delete 2 of my worlds: _buildbatttle7_ and _spleefarena_.
I run `/mv delete buildbatttle7` and `/mv confirm`.
Then I do the same thing for spleefarena.
If I check with FTP I see the the world's folders has been deleted.
Then I restart the server.
After restarting, the worlds that I removed are still there and the world's folder has been atumatic recreated.

**Expected behavior**  
World should be permanently deleted.

**Screenshots**  
I think it is not relevant.

**Comment by benwoo1110** [comment] 2021-06-22 12:17
if the world folder has already been removed, you can use `/mv remove worldname`

**Comment by PappoYT** [comment] 2021-06-22 12:22
When I use `/mv delete` the folder has been deleted BUT when I restart the server the folder has been recreated.

**Comment by benwoo1110** [comment] 2021-06-22 12:24
I can't reproduce with the latest release, the only thing I can say is it may be due to a test build of 5.0.0 in which I don't have time to work on atm.

**Comment by PappoYT** [comment] 2021-06-22 12:27
> I can't reproduce with the latest release, the only thing I can say is it may be due to a test build of 5.0.0 in which I don't have time to work on atm.

Do you suggest me to move back on latest release or wait for next 5.0.0 update?
(if move back, do I need to reconfigure or can I use same yml files?)

**Comment by benwoo1110** [comment] 2021-06-22 12:29
Yes, I suggest testing with the release version.

**Comment by benwoo1110** [comment] 2021-06-26 12:11
MV Deletes world just fine
```
> mv delete test2
[20:10:35 INFO]: Are you sure you want to delete world 'test2'? You cannot undo this action.
[20:10:35 INFO]: Run /mv confirm to continue. This will expire in 10 seconds.
> mv confirm
[20:10:37 INFO]: Deleting world 'test2'...
[20:10:37 INFO]: [Multiverse-Core] World 'test2' was unloaded from Multiverse.
[20:10:38 INFO]: ThreadedAnvilChunkStorage (test2): All chunks are saved
[20:10:38 INFO]: [Multiverse-Core] World 'test2' was unloaded from Bukkit.
[20:10:38 INFO]: [Multiverse-Core] World 'test2' was removed from config.yml
[20:10:38 INFO]: [Multiverse-Core] World 'test2' was DELETED.
[20:10:38 INFO]: World test2 was deleted!
>
```

**Comment by benwoo1110** [comment] 2021-07-21 09:53
Closing as can't reproduce and no further response from the author. Feel free to open a new issue if needed.

**Closed by benwoo1110** 2021-07-21 09:53 UTC
Labels: Bug: Can't Reproduce
