### ISSUE TITLE
Not a string error on 1.16.1

### ISSUE THREAD

**Issue by JasonHorkles** [Multiverse/Multiverse-Core#2317] opened 2020-06-29 20:49 UTC
Whenever the server is started up, "Not a string" gets spammed like 15 times in console. The error stops when I regenerate my worlds file. You can find the current one [here](https://hasteb.in/lulikoba.yaml)

**Comment by Phoenix616** [comment] 2020-06-30 16:04
Can you provide the actual log file with the errors too?

**Comment by JasonHorkles** [comment] 2020-06-30 16:07
https://hasteb.in/evitaliq.sql

**Comment by JasonHorkles** [comment] 2020-06-30 16:11
In the Discord server we concluded it was a problem with the world file but I'm not sure exactly what's causing it

**Comment by NeonCoding** [comment] 2020-08-09 18:43
Had the same problem - not really good at identifying issues, so will leave my log file for people smarter than I to figure out the problem. https://pastebin.com/6baXjkin

**Comment by JasonHorkles** [comment] 2020-08-09 18:49
It's a problem with the world settings file but I'm not sure what exactly
causes it within the file itself

**Comment by NeonCoding** [comment] 2020-08-09 19:55
Sidenote:  I regenned worlds.yml in my multiverse-core folder and left all my adddons configs and had the same issue, so it's not exclusive to core's config whatever's going on.

**Comment by Phoenix616** [comment] 2020-08-09 21:49
I'm now pretty sure it has (at least partially) something to do with old maps and the changes to dimension and custom world support in Bukkit/Spigot. I was getting this error while loading maps that were broken in some other ways too and I assume it's printed due to the dimension being stored as a byte id in the past but they are now string IDs in Minecraft. I suggest testing this with the same worlds that caused it normally but with all map files from the main world's data folder removed.

**Comment by NeonCoding** [comment] 2020-08-10 07:44
Will keep updating as time continues:
Loading just the main world with autoLoad off for all others in the config did not improve the issue
I did not have this issue while loading worlds generated in 1.16
Am backing up server data to test your idea now, will just edit this message once ive tried it.

**Comment by NeonCoding** [comment] 2020-08-10 08:59
I don't overly know what im doing with this, but would it be feasible to change this to the matching string value? (Obviously this wouldn't work at scale, but for testing purposes.)
![NBTExplorer_Fdfk2rK7OP](https://user-images.githubusercontent.com/38158230/89766541-38e8ab80-daf0-11ea-90b2-a24d86792f89.png)

**Comment by shroomdog27** [comment] 2020-08-17 17:28
I was getting this error myself on my server, and became very curious about what was trying to be read as a string. I couldn't see anything in bukkit, craftbukkit, spigot, or Multiverse printing a line that just says "Not a string." So I went searching into the `net.minecraft.server` classes and found it.

In `DynamicOpsNBT`, there was this method 
```java
public DataResult<String> getStringValue(NBTBase nbtbase) {
    return nbtbase instanceof NBTTagString ? DataResult.success(nbtbase.asString()) : DataResult.error("Not a string");
}
```

Here's the code. I became curious about what the game was trying to more or less cast as an NBTTagString, so I modified that class and injected it into the latest spigot jar myself. I changed the above code to this.

```java
@Override
public DataResult<String> getStringValue(NBTBase nbtbase) {
    if(nbtbase instanceof NBTTagString)
        return DataResult.success(nbtbase.asString());
    StringBuilder b = new StringBuilder("Not a string.");
    b.append(System.lineSeparator());
    b.append("This NBTBase object is actually of type ");
    b.append(nbtbase.getClass().toString());
    b.append(System.lineSeparator());
    b.append("This object is represented as the following string $: ");
    b.append(nbtbase.toString());
     new Error(b.toString()).printStackTrace();;
    return DataResult.error("Not a string");
}
```

I got some very interesting results that you can view at [this gist](https://gist.github.com/shroomdog27/e1072c1401ad439c20fe944b2dc13b08).

Overall, I'm not too sure what to think of this, since there is a wide variety of NBT objects that the game is assuming are `NBTString`s but aren't. This doesn't really help at all at trying to figure out what the core, root issue is, but I figure I could post my findings and maybe someone else can give more input.

**Comment by Phoenix616** [comment] 2020-08-17 18:23
@shroomdog27 That method is used when loading the dimension ID of maps (the item, as already indicated [here](https://github.com/Multiverse/Multiverse-Core/issues/2317#issuecomment-671105038)) which was a byte in past versions with an offset of 10 for custom worlds. These could not get converted to string IDs so they will cause this error in the log when loading.

If you notice this error check if you have old map files and if it still happens without them.

**Comment by MinecraftiUndCo** [comment] 2020-09-09 14:42
Do you know any fix for this? Because I also updated our server from 1.15 to 1.16 and get the error at start-up.

**Comment by Phoenix616** [comment] 2020-09-09 14:47
@MinecraftiUndCo besides manually fixing or removing the old map files which cause that, no. You can safely ignore them though if you don't mind that some really old map items wont work anymore.

**Comment by MinecraftiUndCo** [comment] 2020-09-09 14:50
How can I identify which map files are causing the problem and whats the manually fix for them, because I have 25 maps on our buildserver?

**Comment by Phoenix616** [comment] 2020-09-09 15:03
Please see my previous comment and NeonCoding's ones on that subject. To fix it you would basically need to set the dimension nbt tag in the map's .dat file to the correct dimension name which the map belonged to.

**Comment by MinecraftiUndCo** [comment] 2020-09-09 15:14
@Phoenix616 So what will happen if I just delete the map_x.dat files? And if I want to change it, should I set it to "minecraft:overworld" or what are the new, correct values?

**Comment by Phoenix616** [comment] 2020-09-09 15:44
Besides the map no longer working I don't think anything would happen but
make sure to take backups. And while the default world might stop the error
it wouldn't fix the map itself. If you want to really fix it you would need
to find the correct corresponding world.

**Comment by uncovery** [comment] 2020-09-10 02:00
It would be great to have a plugin that can check worlds for this issue. Can anyone identify which action on server start is causing this? Is it something that Multiverse does?

**Comment by JasonHorkles** [comment] 2020-10-10 20:11
Fixed in paper [build #220](https://github.com/PaperMC/Paper/commit/f3927b25ebb6cff982a97d82cb424c137fedac9f)

**Comment by nicegamer7** [comment] 2020-10-11 03:07
Thanks for letting us know. While it's not our responsibility, I'd just like to keep this issue open until the issue is fixed in Spigot as well.

**Comment by nicegamer7** [comment] 2020-10-13 04:42
I've reported it to spigot, https://hub.spigotmc.org/jira/browse/SPIGOT-6181.

**Comment by benwoo1110** [comment] 2021-05-16 02:47
Fixed long ago by paper, so closing this.

**Closed by benwoo1110** 2021-05-16 02:47 UTC
Labels: Bug: Confirmed, Resolution: Unrelated to MV, Severity: Minor
