### ISSUE TITLE
Feature Request - Allow world access but disallow teleport to it

### ISSUE THREAD

**Issue by Dycus** [Multiverse/Multiverse-Core#2274] opened 2020-06-02 21:31 UTC
There doesn't seem to be any way to allow access to a world without also allowing players to teleport to it. 

I want a vanilla Minecraft experience where players access the nether and end through their respective portals, but with an additional creative test world players can teleport to and from.
In order for players to access the nether and end, they need permission with multiverse.access.NAME. However, granting this permission also allows teleporting to those worlds, which I don't want.

**Comment by benwoo1110** [comment] 2020-10-12 07:59
Duplicate of #2256

**Closed by benwoo1110** 2020-10-12 07:59 UTC
Labels: Resolution: Duplicate, Type: Idea
