### ISSUE TITLE
Multiverse Error

### ISSUE THREAD

**Issue by lukemango** [Multiverse/Multiverse-Core#2009] opened 2019-06-01 22:26 UTC
https://pastebin.com/ftwmWUyH

**Comment by MonstahGames** [comment] 2019-06-02 10:28
TravelAgent is non existant in 1.14

**Comment by Jadiction** [comment] 2019-06-03 10:21
Please read my comment on #1998. Ticket closed. Duplicate of #1998

**Closed by Jadiction** 2019-06-03 10:21 UTC
Labels: Duplicate
