### ISSUE TITLE
MVPortalListener.entityPortalCreate issue

### ISSUE THREAD

**Issue by bloggy** [Multiverse/Multiverse-Core#2064] opened 2019-08-06 10:04 UTC
[12:02:34 INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.0.0-b766
>.... [12:02:34 WARN]: [Multiverse-Core] "Multiverse-Core v4.0.0-b766" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

I am on paper spigot 1.14.4
just upgraded.

what does this error mean?

**Comment by bardiharborow** [comment] 2019-08-06 13:20
Duplicate of #2000.

**Closed** 2019-08-06 23:06 UTC
Labels: Duplicate
