### ISSUE TITLE
Multi-verse breaks custom advancements from loading.

### ISSUE THREAD

**Issue by mibby** [Multiverse/Multiverse-Core#1842] opened 2017-07-21 14:11 UTC
Paper dev 1153 (Spigot 1.12)
Multiverse dev 736

With multiverse installed, custom advancements added to the main world data folder break from loading correctly.

Custom advancement pack for testing.
https://www.planetminecraft.com/project/blazeandcave-s-advancements-pack-1-12/

Removing multiverse, advancements load and display perfectly fine. Perhaps you could take a look @dumptruckman?

**Comment by mibby** [comment] 2017-07-24 00:03
Update on the issue after some investigating. It seems to load the advancements in the data folder of the world that is sorted first in alphabetical order, not from the main "world" data folder. So if you have a custom world named 'void', you must place the advancements in that world's data folder for it to read and load correctly when multiverse is installed.

**Comment by ryantheleach** [comment] 2017-07-24 00:39
@mibby at a guess, this is more likely to be a Spigot bug. you may have better luck reporting it to them.

**Comment by mibby** [comment] 2017-07-24 01:43
@ryantheleach I'm not sure it is a Spigot bug because when I tried the plugin MyWorlds (https://www.spigotmc.org/resources/myworlds.39594/) it worked fine with advancements just in the primary 'world' world data folder. They had an import for Multiverse world configuration so I just swapped it in and had it load the same worlds to test.

**Comment by q220** [comment] 2017-08-03 23:56
I noticed this as well, especially with location bound advancement's. I'm not sure however if it is because of Multiverse or Spigot, because according to what I read in the Spigot API, there is no support for advancements per world in a multworld environment. It does handle the world selector when making the advancement, but that only applies to overworld, nether, ... and not as in muliple overworld worlds.

When adding an advancement to my 'primary world' set by MV config, it seems to only check that overworld in particular and not the others.

**Comment by tenebraemaximus** [comment] 2017-08-06 12:50
I've been experiencing this bug too. Functions load fine, but advancements do not. When players rejoin the server after a restart, all progress on custom advancements will be gone.

**Comment by LinearBotSystems** [comment] 2017-08-07 21:54
The problem is Minecraft 1.12 its binds the server settings only to the first world now. Especially the advancements so you can't even turn it off in a custom world without a special plugin. This will be fixed in the next version https://minecraft.gamepedia.com/1.13 .(Basically Mojang is doing the work for spigot and mv but I doubt they are happy about it) 

> General

Data packs

    Like resource packs, but for loot tables, advancements, functions, etc.
        Can be changed from world to server side.[3][4]
        Used by placing them into the world or server file, and it is also possible to use multiple data packs, or none at all.[5][6]
    Data packs are .zip files or folders with a pack.mcmeta in the root. See: Tutorials/Creating a resource pack#pack.mcmeta[6]
    Structures will load from (world)/generated/structures/(namespace)/(file).nbt before checking data packs.
        However, this directory should not be used to distribute structures. Instead, move these files into data packs.


You have then also custom recipes but it is very likely that other things break again because 

> 
Block ID

    The upper limit of the block ID disappears[17][18]

I'm not sure but this could mean that  some Char types become Integer which breaks the Spigorts api and many plugins

**Comment by aeonlamb** [comment] 2017-09-29 16:12
Having this issue too, problem exists on craftbukkit/spigot/paper 1.12.2

Even if this is supposedly a problem with vanilla, I feel like there should be some workaround to get it working...

**Comment by Astra3** [comment] 2018-08-18 19:49
So, 1.13 is here and I don't still see anywhere this feature to have per world datapacks.
And there is also an issue when something contains coordinates and it is included in minecraft:tick tag.

**Comment by TheSaltyPug** [comment] 2019-07-07 18:19
Sorry for reviving an old thread, but 1.14.3 is here and data packs still aren't implemented. there is a feature that I would very much like for my server. data packs are essential in 1.14.

Creating a world should make a datapacks folder, and the datapacks should load per-world. 

While you're at it, might as well throw in a reload command that does an unload and a load, just like minecraft:reload. This would be especially useful to develop a datapack in one world, and not have to reload the entire plugin but just the world!

**Comment by dumptruckman** [comment] 2019-07-08 03:34
While it would be nice to have such a feature, there is not API for achieving this in Bukkit. Basically, either Spigot needs to support loading per world datapacks by default, add some kind of api to set it per player, or something similar.

If MyWorlds some how gets around this it is likely related to NMS code which is off limits for Bukkit only plugins like Multiverse.

**Comment by benwoo1110** [comment] 2020-10-06 16:43
I don't think this will be implemented any time soon, unless bukkit API can control data pack which seems unlike. Till then, I will have to close this issue. Sorry!

**Closed by benwoo1110** 2020-10-06 16:43 UTC
Labels: Bug, Can't Fix/Won't Fix
