### ISSUE TITLE
Per-World time

### ISSUE THREAD

**Issue by IanLulz** [Multiverse/Multiverse-Core#1824] opened 2017-06-18 15:48 UTC
Per-World time still isn't a thing or isn't working. Would it be possible to add this? :)

**Comment by Supuhstar** [comment] 2018-09-09 19:53
Please, I hope so. I want my Creative worlds to stay day, and Survival to cycle normally

**Comment by Supuhstar** [comment] 2018-09-10 01:37
Duplicate of #79

**Comment by Jadiction** [comment] 2019-06-03 04:11
If you wanted a specific time set for a world, you could accomplish this by setting the gamerule "doDaylightCycle" to false. Once you specify the time for that world, it will no longer change. I'm not seeing much use of a per-world configuration of time other than that. Due to this, this configuration being added is unlikely unless a good reason is specified. If that is the case, please re-open a ticket!

**Closed by Jadiction** 2019-06-03 04:11 UTC

**Comment by Supuhstar** [comment] 2019-06-04 16:39
When everyone sleeps in a Survival world (might be a small personal world
with 1 person), I never want that to cause every single other world to skip
nighttime, especially those which rely on nighttime for its different
gameplay mechanics

**Comment by dumptruckman** [comment] 2019-06-04 18:27
@Supuhstar honestly, that sounds like something the server should be handling better. I would suggest opening this as a craftbukkit/spigot issue.

**Comment by IanLulz** [comment] 2019-06-04 18:31
@dumptruckman How is this a Spigot/CB issue? Neither of them introduce multi-world support, so times in multi-world server setups aren’t their concern.

**Comment by dumptruckman** [comment] 2019-06-04 18:33
Bukkit has a multi world API. It is the reason why this plugin exists as a Bukkit plugin and not an NMS based plugin that breaks every single MC update.

**Comment by dumptruckman** [comment] 2019-06-04 18:36
To expand on this: Multiverse (and any other plugin that creates worlds) makes a simple request asking the server to create a new world or to load a world from file. It is a feature of the server itself. Multiverse-Core is essentially just an interface for players and server admins to be able to create and load worlds from the console or in game.

**Comment by Jadiction** [comment] 2019-06-06 01:17
I use this plugin: https://dev.bukkit.org/projects/customtime
for per-world time modifications. For example, you can make day time 10 minutes and nighttime 2 minutes, or day/night disabled as well.

**Comment by timschwab** [comment] 2021-06-07 01:32
For those interested, I have created a Spigot issue for this (finally, after nearly a decade haha). You can find it [here](https://hub.spigotmc.org/jira/browse/SPIGOT-6496). Any comments confirming this is an issue would likely be helpful.
