### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by KazotaruuMC** [Multiverse/Multiverse-Core#3078] opened 2024-07-27 19:15 UTC
### `/mv version -p` output

https://paste.gg/d1cc03ec2b5649dda5ae668f6908360b

### Server logs

https://paste.gg/p/anonymous/c1e5b5aa45fc4ee988b0e33558c30153

### Server Version

```shell
version
[21:15:03 INFO]: This server is running Paper version 1.21-39-master@aa8d38d (2024-06-29T09:10:10Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are 72 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21-109-5a5035b (MC: 1.21)
```

### Bug Description

[21:05:52 WARN]: [Multiverse-Core] "Multiverse-Core v4.3.1-b861" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--]

### Steps to reproduce

look console

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by AjnebAlReves** [comment] 2024-07-27 19:27
its a known issue lol

**Comment by zax71** [comment] 2024-07-27 20:12
Duplicate of #2000

**Closed by zax71** 2024-07-27 20:12 UTC
Labels: Bug: Unconfirmed
