### ISSUE TITLE
1.14.1 console error

### ISSUE THREAD

**Issue by successed** [Multiverse/Multiverse-Core#2004] opened 2019-05-26 10:00 UTC
[12:59:00 ERROR]: Could not pass event PlayerPortalEvent to Multiverse-Core v3.0.0-SNAPSHOT-b761
java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerPortalEvent.getPortalTravelAgent()Lorg/bukkit/TravelAgent;
        at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerPortal(MVPlayerListener.java:307) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor129.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.1.jar:git-Paper-43]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.1.jar:git-Paper-43]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.1.jar:git-Paper-43]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:534) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.EntityPlayer.a(EntityPlayer.java:843) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.Entity.doPortalTick(Entity.java:2165) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.Entity.entityBaseTick(Entity.java:397) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.EntityLiving.entityBaseTick(EntityLiving.java:236) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.Entity.tick(Entity.java:369) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2273) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.EntityHuman.tick(EntityHuman.java:150) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:418) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.PlayerConnection.tick(PlayerConnection.java:146) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:259) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1201) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.1.jar:git-Paper-43]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by kakd** [comment] 2019-05-27 06:54
TravelAgent was removed in Spigot 1.14. In order to reproduce this error, walk through a nether portal.

**Comment by successed** [comment] 2019-05-30 19:31
[22:30:45 ERROR]: Could not pass event PlayerPortalEvent to Multiverse-Core v3.0.0-SNAPSHOT-b761
java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerPortalEvent.getPortalTravelAgent()Lorg/bukkit/TravelAgent;
        at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerPortal(MVPlayerListener.java:307) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor122.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.2.jar:git-Paper-55]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.2.jar:git-Paper-55]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-55]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:534) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.EntityPlayer.a(EntityPlayer.java:843) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.Entity.doPortalTick(Entity.java:2165) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.Entity.entityBaseTick(Entity.java:397) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.EntityLiving.entityBaseTick(EntityLiving.java:240) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.Entity.tick(Entity.java:369) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2279) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.EntityHuman.tick(EntityHuman.java:150) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:418) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.PlayerConnection.tick(PlayerConnection.java:146) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:259) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1201) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-55]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by Jadiction** [comment] 2019-06-03 10:09
Please read my comment on the #1998 Ticket is now closed. Duplicate of https://github.com/Multiverse/Multiverse-Core/issues/1998

**Closed by Jadiction** 2019-06-03 10:09 UTC
Labels: Duplicate
