### ISSUE TITLE
World folder remains on delete

### ISSUE THREAD

**Issue by ScuroK** [Multiverse/Multiverse-Core#2369] opened 2020-07-27 13:44 UTC
Hi. Im using Build #777 on paper 1.16.1

When i delete a nether world using /mv delete the empty world folder remains on my server and i have to delete it manually.
i dont get any errors in console.

can you please fix this?

**Comment by nicegamer7** [comment] 2020-07-28 20:24
I'm going to close this as a duplicate of #2349.

**Closed by nicegamer7** 2020-07-28 20:24 UTC
