### ISSUE TITLE
[Idea]: Folia Support

### ISSUE THREAD

**Issue by Yomamaeatstoes** [Multiverse/Multiverse-Core#2907] opened 2023-04-04 02:52 UTC
### Describe the feature

Folia Support

Granted at the beginning some features won't be available

### How is the feature useful to all Multiverse users?

Because Folia is much more efficient and it is good to do work early so you won't have to do work later.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by benwoo1110** [comment] 2023-04-04 15:27
Duplicate of #2901

**Closed by benwoo1110** 2023-04-04 15:27 UTC
Labels: Type: Idea, Resolution: Duplicate
