### ISSUE TITLE
"Multiverse-Core v4.0.0-b766"  -  event is Deprecated

### ISSUE THREAD

**Issue by EchocallingEarth** [Multiverse/Multiverse-Core#2061] opened 2019-08-03 05:18 UTC
The following showed up during restart and continues to do so. After looking into I have found no similar reports here and wanted to report it as it states to do accordingly.

This is a server warning during startup.

> _[22:07:20 WARN]: [Multiverse-Core] "Multiverse-Core v4.0.0-b766" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman]._ 

I will provide any additional information I can to assist. Thank you for looking into this warning and handling as needed.

Complete startup Log provided here in case you need something that it provides:

https://pastebin.com/vPWKYMbr

Respectfully ~ Echo

**Comment by dumptruckman** [comment] 2019-08-04 02:51
Duplicate of #2000.

**Closed by dumptruckman** 2019-08-04 02:51 UTC
