### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by var1nthon** [Multiverse/Multiverse-Core#3041] opened 2023-11-03 11:49 UTC
### `/mv version -p` output

[Multiverse-Core] Multiverse-Core Version: 4.3.12 [Multiverse-Core] Bukkit Version: git-Paper-262 (MC: 1.20.2) [Multiverse-Core] Loaded Worlds: [{"MVWorld@270679523":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"spawn"}}, {"MVWorld@1647376550":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world"}}] [Multiverse-Core] Multiverse Plugins Loaded: 0 [Multiverse-Core] Economy being used: Simple Item Economy [Multiverse-Core] Permissions Plugin: Bukkit Permissions (SuperPerms) [Multiverse-Core] Dumping Config Values: (version 2.9) [Multiverse-Core]   enforceaccess: false [Multiverse-Core]   prefixchat: false [Multiverse-Core]   prefixchatformat: [%world%]%chat% [Multiverse-Core]   useasyncchat: true [Multiverse-Core]   teleportintercept: true [Multiverse-Core]   firstspawnoverride: true [Multiverse-Core]   displaypermerrors: true [Multiverse-Core]   enablebuscript: true [Multiverse-Core]   globaldebug: 0 [Multiverse-Core]   silentstart: false [Multiverse-Core]   messagecooldown: 5000 [Multiverse-Core]   version: 2.9 [Multiverse-Core]   firstspawnworld: world [Multiverse-Core]   teleportcooldown: 3000 [Multiverse-Core]   defaultportalsearch: true [Multiverse-Core]   portalsearchradius: 128 [Multiverse-Core]   autopurge: true [Multiverse-Core] Special Code: FRN002

### Server logs

https://paste.gg/p/anonymous/b3974c7259ed40c0b857b11c085a4d58

### Server Version

```shell
This server is running Paper version git-Paper-262 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 8493340)
You are running the latest version
Previous version: git-Paper-260 (MC: 1.20.2)
```

### Bug Description

"Multiverse-Core v4.3.12" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].

### Steps to reproduce

1. Start a server with multiverse installed.
2. Run 'run_survival1.bat' (paper-1.20.2-262.jar)
3. Terminal shows the message of the Multiverse plugin in yellow.

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by zax71** [comment] 2023-11-03 11:56
Duplicate of #2000

**Closed by zax71** 2023-11-03 11:56 UTC
Labels: Bug: Unconfirmed

**Comment by var1nthon** [comment] 2023-11-07 05:09
Thank u
