### ISSUE TITLE
Alias resetting after reboot

### ISSUE THREAD

**Issue by Eppich207** [Multiverse/Multiverse-Core#2179] opened 2020-02-22 22:36 UTC
Using the latest version of mvc, mvp, and mvi; I noticed that when I am configuring prefixes and aliases with mv config and mvm set respectively and then go to restart my server the alias gets deleted and the prefix goes back to the world name.

This is what I'm doing so far:
`/mvm set alias HUB`
`/mvm set style bold`
`/mvm set color lightpurple`
`/mv config prefixchatformat [%world%]%chat%` (default)

Whereafter I confirm by typing in chat that it is indeed working showing in purple [HUB], but then as I go and restart my server and relog the alias and colors are gone. Returning to normal white text

Could someone help me with this? I tried searching before but have found no one with this issue.

**Comment by benwoo1110** [comment] 2020-03-28 09:04
Can you try and change the alias while server is **off**, under world.yml file `alias: <name>`.

Also make sure you are using a multiverse version compatible with your server version.

**Comment by benwoo1110** [comment] 2020-10-07 09:03
Closing this as no one seems to be able to reproduce the issue. If you still face issues, you can open a new issue or come to our discord at https://discord.gg/NZtfKky

**Closed by benwoo1110** 2020-10-07 09:03 UTC
Labels: Can't Reproduce
