### ISSUE TITLE
Nether Portals not tp mobs and items

### ISSUE THREAD

**Issue by TheCactusMonkey** [Multiverse/Multiverse-Core#1856] opened 2017-08-14 10:45 UTC
I have one problem when im using Multiverse Nether Portals, if i trow items and push a mob thru a nether portal the item and the mob disappears. So it's inpossible to make like ZombiePigman farms and more. Anyone else have this problem and have anyone solved it?

//TheCactusMonkey

**Comment by TheCactusMonkey** [comment] 2017-10-30 20:33
ANYONE KNOWS!?!?!?

**Comment by Castiella** [comment] 2018-04-15 19:14
Yeah having this issue too, presuming plugin dev is inactive now?

**Comment by Nightkiller4375** [comment] 2019-07-16 06:47
This appears to still be an issue in the latest version of the plugin in 1.14.3. No entities are able to travel through portals except players. Entities just act like there's nothing there.

**Comment by Castiella** [comment] 2019-08-30 13:37
Also having this issue. Following.

**Comment by craftedpure** [comment] 2019-10-16 01:43
I can tell you this, I sent cats thru a portal in one of our MV worlds, and just figure they died. The NP is in a village, so raids are farmed there. Pillagers would be lost to the portal also.  I was in out 1st world on the server and saw the 2 cats in the nether near a portal...i though, hey that's strange, went thru the nether to the over world and BOOM! Pillagers and zombies galore!  So it appears the Nether portals are linked in worlds for players, but entity's will end up in another worlds nether on MV.

Hope that helps the content creator to find where the issue is, maybe. 😁

**Comment by djytw** [comment] 2019-10-29 18:05
may related to Multiverse/Multiverse-NetherPortals#72?

**Comment by benwoo1110** [comment] 2020-10-06 16:25
This should be fixed by https://github.com/Multiverse/Multiverse-NetherPortals/pull/182

**Closed by benwoo1110** 2020-10-06 16:25 UTC
Labels: Bug, Unconfirmed
