### ISSUE TITLE
World Corruption 1.8.3

### ISSUE THREAD

**Issue by lanky5544** [Multiverse/Multiverse-Core#1557] opened 2015-03-10 21:20 UTC
i get this error every time server starts and no world loads up.
[08:14:22] [Server thread/INFO]: [Multiverse-Core] Enabling Multiverse-Core v2.5-b691
[08:14:22] [Server thread/INFO]: [Multiverse-Core] [AllPay] - Version 13.0 - hooked into Essentials Economy for Multiverse-Core v2.5-b691
[08:14:23] [Server thread/WARN]: [Multiverse-Core] Exception while loading value for environment
[08:14:23] [Server thread/WARN]: [Multiverse-Core] Exception while loading value for environment
[08:14:23] [Server thread/WARN]: [Multiverse-Core] Exception while loading value for environment
[08:14:23] [Server thread/WARN]: [Multiverse-Core] Exception while loading value for environment
[08:14:23] [Server thread/WARN]: [Multiverse-Core] Exception while loading value for environment
[08:14:23] [Server thread/WARN]: [Multiverse-Core] Exception while loading value for environment
[08:14:23] [Server thread/WARN]: java.lang.NullPointerException
[08:14:23] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.WorldServer.<init>(WorldServer.java:57)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.createWorld(CraftServer.java:893)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:463)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[08:14:23] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:421)
[08:14:23] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:402)
[08:14:23] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:377)
[08:14:23] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:676)
[08:14:23] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:306)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316)
[08:14:23] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416)
[08:14:23] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382)
[08:14:23] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337)
[08:14:23] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257)
[08:14:23] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522)
[08:14:23] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[08:14:23] [Server thread/ERROR]: [Multiverse-Core] The world 'plotworld' could NOT be loaded because it contains errors!
[08:14:23] [Server thread/ERROR]: [Multiverse-Core] Try using Chukster to repair your world! 'plotworld'
[08:14:23] [Server thread/ERROR]: [Multiverse-Core] http://forums.bukkit.org/threads/admin-chunkster.8186/
[08:14:23] [Server thread/WARN]: java.lang.NullPointerException
[08:14:23] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.WorldServer.<init>(WorldServer.java:57)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.createWorld(CraftServer.java:893)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:463)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[08:14:23] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:421)
[08:14:23] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:402)
[08:14:23] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:377)
[08:14:23] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:676)
[08:14:23] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:306)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316)
[08:14:23] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416)
[08:14:23] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382)
[08:14:23] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337)
[08:14:23] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257)
[08:14:23] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522)
[08:14:23] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[08:14:23] [Server thread/ERROR]: [Multiverse-Core] The world 'wild' could NOT be loaded because it contains errors!
[08:14:23] [Server thread/ERROR]: [Multiverse-Core] Try using Chukster to repair your world! 'wild'
[08:14:23] [Server thread/ERROR]: [Multiverse-Core] http://forums.bukkit.org/threads/admin-chunkster.8186/
[08:14:23] [Server thread/WARN]: java.lang.NullPointerException
[08:14:23] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.WorldServer.<init>(WorldServer.java:57)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.createWorld(CraftServer.java:893)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:463)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[08:14:23] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:421)
[08:14:23] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:402)
[08:14:23] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:377)
[08:14:23] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:676)
[08:14:23] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:306)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356)
[08:14:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316)
[08:14:23] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416)
[08:14:23] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382)
[08:14:23] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337)
[08:14:23] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257)
[08:14:23] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522)
[08:14:23] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[08:14:23] [Server thread/ERROR]: [Multiverse-Core] The world 'creative' could NOT be loaded because it contains errors!
[08:14:23] [Server thread/ERROR]: [Multiverse-Core] Try using Chukster to repair your world! 'creative'
[08:14:23] [Server thread/ERROR]: [Multiverse-Core] http://forums.bukkit.org/threads/admin-chunkster.8186/

**Comment by TWSSYesterday** [comment] 2015-03-11 01:06
Corrupt world: "Try using Chukster to repair your world! 'creative'" and "Try using Chukster to repair your world! 'plotworld"

**Comment by lanky5544** [comment] 2015-03-11 06:52
I have already tried this, but still doesnt work, i have tried creating world too and getting this error
[06:50:07] [Server thread/WARN]: java.lang.NullPointerException
[06:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.World.<init>(World.java:197)
[06:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.WorldServer.<init>(WorldServer.java:57)
[06:50:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.createWorld(CraftServer.java:893)
[06:50:07] [Server thread/WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:463)
[06:50:07] [Server thread/WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[06:50:07] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:421)
[06:50:07] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:229)
[06:50:07] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114)
[06:50:07] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[06:50:07] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
[06:50:07] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[06:50:07] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:897)
[06:50:07] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[06:50:07] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[06:50:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
[06:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133)
[06:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968)
[06:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[06:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[06:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[06:50:07] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[06:50:07] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[06:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
[06:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:714)
[06:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
[06:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:655)
[06:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:558)
[06:50:07] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[06:50:07] [Server thread/ERROR]: [Multiverse-Core] The world 'Test' could NOT be loaded because it contains errors!
[06:50:07] [Server thread/ERROR]: [Multiverse-Core] Try using Chukster to repair your world! 'Test'
[06:50:07] [Server thread/ERROR]: [Multiverse-Core] http://forums.bukkit.org/threads/admin-chunkster.8186/
[06:50:07] [Server thread/ERROR]: [Multiverse-Core] Failed to Create/Load the world 'Test'
[06:50:07] [Server thread/INFO]: LankyK0ng: FAILED.[m

**Comment by TWSSYesterday** [comment] 2015-03-11 19:47
Mind adding me on skype? liam.newman97, this is a world corruption issue...

**Comment by lanky5544** [comment] 2015-03-12 08:32
this is not a curruption issue because when using same Multiverse-core version with 1.8 both world load fine and I create world with a problem but when using 1.8.3 it breaks it

**Comment by lanky5544** [comment] 2015-03-12 23:36
After a bit of work managed to get this working but appears the latest Multiverse has some issues with Spigot/Craftbukkit 1.8.3, so for now it is working but I cant see people doing what i did to fix the issue

**Comment by LiveMineCraft** [comment] 2015-04-13 12:07
Greetings.  I'm experiencing some technical difficulty like lanky5544.  I'm running Spigot 1.8.1 and agree with his research.  I may just re-install some plugins to possibly fix this problem and see if its World Edit causing the issue to the plot.  My partner and I cannot create a plotworld using the generator but all worlds from /mv create other than "CleanRoomGenerator" will work. The /mv load and /mv import will not activate the unloaded names and trying so gives the internal error msgs and details to console, that detail is below.
Hope this info below may be of help to solve problem.
Using spigots PlotMe-DefaultGenerator and Multiverse prior to my trouble I was using World Edit testing plot where I had used //paste and //undo a few times and noticed a large sink hole nearby adjacent plot.. players noticed and could see beyond bedrock and able to walk over that area as if floating and disappearing to others.. time goes on and slowly plot world dissolves.  Exiting the plotworld and coming back everything is normal but then dissolving repeats.  
Error info from console:
13.04 04:40:53 [Multicraft] Skipped 11 lines due to rate limit (30/s)
13.04 04:40:28 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
13.04 04:40:28 [Server] WARN at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
13.04 04:40:28 [Server] WARN at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
13.04 04:40:28 [Server] WARN at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
13.04 04:40:28 [Server] WARN at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
13.04 04:40:28 [Server] WARN at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
13.04 04:40:28 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645)
13.04 04:40:28 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
13.04 04:40:28 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
13.04 04:40:28 [Server] WARN at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:897)
13.04 04:40:28 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
13.04 04:40:28 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
13.04 04:40:28 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
13.04 04:40:28 [Server] WARN at com.onarandombox.MultiverseCore.commands.LoadCommand.runCommand(LoadCommand.java:36)
13.04 04:40:28 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorld(WorldManager.java:364)
13.04 04:40:28 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:377)
13.04 04:40:28 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:402)
13.04 04:40:28 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:427)
13.04 04:40:28 [Server] WARN at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:56)
13.04 04:40:28 [Server] WARN at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:79)
13.04 04:40:28 [Server] WARN at com.onarandombox.MultiverseCore.MVWorld.readSpawnFromWorld(MVWorld.java:410)
13.04 04:40:28 [Server] WARN at com.onarandombox.MultiverseCore.utils.SimpleBlockSafety.playerCanSpawnHereSafely(SimpleBlockSafety.java:83)
13.04 04:40:28 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getBlockAt(CraftWorld.java:558)
13.04 04:40:28 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getBlockAt(CraftWorld.java:88)
13.04 04:40:28 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getChunkAt(CraftWorld.java:124)
13.04 04:40:28 [Server] WARN at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:95)
13.04 04:40:28 [Server] WARN at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116)
13.04 04:40:28 [Server] WARN at net.minecraft.server.v1_8_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:148)
13.04 04:40:28 [Server] WARN net.minecraft.server.v1_8_R1.ReportedException: Exception generating new chunk
Greetings.  I'm experiencing some technical difficulty like lanky5544.  I may just re-install some plugins to possibly fix the problem.  My partner and I cannot create a plotworld using the generator but all worlds from /mv create other than "CleanRoomGenerator" will work. The /mv load and /mv import will not activate the unloaded names and trying so gives the internal error msgs and details to console, that detail is below.
Hope this info below may be of help to solve problem.
Using spigots PlotMe-DefaultGenerator and Multiverse prior to my trouble I was using World Edit testing plot where I had used //paste and //undo a few times and noticed a large sink hole nearby adjacent plot.. players noticed and could see beyond bedrock and able to walk over that area as if floating and disappearing to others.. time goes on and slowly plot world dissolves.  Exiting the plotworld and coming back everything is normal but then dissolving repeats.  
Error info from console:
13.04 04:40:53 [Multicraft] Skipped 11 lines due to rate limit (30/s)
13.04 04:40:28 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
13.04 04:40:28 [Server] WARN at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
13.04 04:40:28 [Server] WARN at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
13.04 04:40:28 [Server] WARN at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
13.04 04:40:28 [Server] WARN at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
13.04 04:40:28 [Server] WARN at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
13.04 04:40:28 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645)
13.04 04:40:28 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
13.04 04:40:28 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
13.04 04:40:28 [Server] WARN at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:897)
13.04 04:40:28 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
13.04 04:40:28 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
13.04 04:40:28 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
13.04 04:40:28 [Server] WARN at com.onarandombox.MultiverseCore.commands.LoadCommand.runCommand(LoadCommand.java:36)
13.04 04:40:28 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorld(WorldManager.java:364)
13.04 04:40:28 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:377)
13.04 04:40:28 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:402)
13.04 04:40:28 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:427)
13.04 04:40:28 [Server] WARN at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:56)
13.04 04:40:28 [Server] WARN at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:79)
13.04 04:40:28 [Server] WARN at com.onarandombox.MultiverseCore.MVWorld.readSpawnFromWorld(MVWorld.java:410)
13.04 04:40:28 [Server] WARN at com.onarandombox.MultiverseCore.utils.SimpleBlockSafety.playerCanSpawnHereSafely(SimpleBlockSafety.java:83)
13.04 04:40:28 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getBlockAt(CraftWorld.java:558)
13.04 04:40:28 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getBlockAt(CraftWorld.java:88)
13.04 04:40:28 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getChunkAt(CraftWorld.java:124)
13.04 04:40:28 [Server] WARN at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:95)
13.04 04:40:28 [Server] WARN at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116)
13.04 04:40:28 [Server] WARN at net.minecraft.server.v1_8_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:148)
13.04 04:40:28 [Server] WARN net.minecraft.server.v1_8_R1.ReportedException: Exception generating new chunk

**Comment by TWSSYesterday** [comment] 2015-06-08 00:13
Still occurs? I can't reproduce.

**Comment by Pendar2** [comment] 2015-06-09 06:53
I had a similar issue, not sure it it's the same. Make sure you have the correct name of your world in the PlotMe-DefaultGenerator's config.

**Comment by FernFerret** [comment] 2016-04-20 21:29
Closing due to issue age (sorry). We slacked off on our issues. If you're still having this issue, please read up on [submitting a bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and post the details with a more recent server/multiverse version. Sorry again!

**Closed by FernFerret** 2016-04-20 21:29 UTC
Labels: Unrelated to MV
