### ISSUE TITLE
Multiverse keeps changing spawn of hostile mobs to false. 

### ISSUE THREAD

**Issue by darkmage4** [Multiverse/Multiverse-Core#2401] opened 2020-09-05 19:51 UTC
### Information

* **Server version:**   paper 1.16.2

* **Full output of `/mv version -b`:** 

* **Server log:** 
`5.09 15:48:58 [Server] INFO Multiverse-Inventories Version: 3.0.0-b459
05.09 15:48:58 [Server] INFO First Run: false
05.09 15:48:58 [Server] INFO Using Bypass: false
05.09 15:48:58 [Server] INFO Default Ungrouped Worlds: false
05.09 15:48:58 [Server] INFO Using GameMode Profiles: false
05.09 15:48:58 [Server] INFO === Groups ===
05.09 15:48:58 [Server] INFO default: {Worlds: [world, world_the_end, world_nether], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
05.09 15:48:58 [Server] INFO group1: {Worlds: [smp, smp_the_end, smp_nether], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
05.09 15:48:58 [Server] INFO [Multiverse-Core] Multiverse-Core Version: 4.1.0-b775
05.09 15:48:58 [Server] INFO [Multiverse-Core] Bukkit Version: git-Paper-148 (MC: 1.16.2)
05.09 15:48:58 [Server] INFO [Multiverse-Core] Loaded Worlds: [{"MVWorld@2038602445":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"sky"}}, {"MVWorld@1680610433":{"Gen":"null","Type":"NORMAL","Env":"THE_END","Name":"smp_the_end"}}, {"MVWorld@1737546402":{"Gen":"uSkyBlock","Type":"NORMAL","Env":"NORMAL","Name":"skyworld"}}, {"MVWorld@1857805684":{"Gen":"null","Type":"NORMAL","Env":"NETHER","Name":"smp_nether"}}, {"MVWorld@1445611316":{"Gen":"IridiumSkyblock","Type":"FLAT","Env":"NORMAL","Name":"IridiumSkyblock"}}, {"MVWorld@1386666348":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"factions"}}, {"MVWorld@855792720":{"Gen":"null","Type":"NORMAL","Env":"THE_END","Name":"world_the_end"}}, {"MVWorld@1777667288":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"world"}}, {"MVWorld@56780601":{"Gen":"null","Type":"NORMAL","Env":"NETHER","Name":"world_nether"}}, {"MVWorld@125141894":{"Gen":"IridiumSkyblock","Type":"FLAT","Env":"NETHER","Name":"IridiumSkyblock_nether"}}, {"MVWorld@1806418860":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"SMP"}}, {"MVWorld@1669089213":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"buildings"}}, {"MVWorld@1111320414":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"Stream"}}]
05.09 15:48:58 [Server] INFO [Multiverse-Core] Multiverse Plugins Loaded: 3
05.09 15:48:58 [Server] INFO [Multiverse-Core] Economy being used: Essentials Economy
05.09 15:48:58 [Server] INFO [Multiverse-Core] Permissions Plugin: Bukkit Permissions (SuperPerms)
05.09 15:48:58 [Server] INFO [Multiverse-Core] Dumping Config Values: (version 2.9)
05.09 15:48:58 [Server] INFO [Multiverse-Core]  messagecooldown: 5000
05.09 15:48:58 [Server] INFO [Multiverse-Core]  teleportcooldown: 1000
05.09 15:48:58 [Server] INFO [Multiverse-Core]  worldnameprefix: false
05.09 15:48:58 [Server] INFO [Multiverse-Core]  worldnameprefixFormat: %chat%
05.09 15:48:58 [Server] INFO [Multiverse-Core]  enforceaccess: false
05.09 15:48:58 [Server] INFO [Multiverse-Core]  displaypermerrors: true
05.09 15:48:58 [Server] INFO [Multiverse-Core]  teleportintercept: true
05.09 15:48:58 [Server] INFO [Multiverse-Core]  firstspawnoverride: true
05.09 15:48:58 [Server] INFO [Multiverse-Core]  firstspawnworld: world
05.09 15:48:58 [Server] INFO [Multiverse-Core]  debug: 0
05.09 15:48:58 [Server] INFO [Multiverse-Core] Special Code: FRN002
05.09 15:48:58 [Server] INFO [Multiverse-Inventories] Multiverse-Inventories Version: 3.0.0-b459
05.09 15:48:58 [Server] INFO [Multiverse-Inventories] First Run: false
05.09 15:48:58 [Server] INFO [Multiverse-Inventories] Using Bypass: false`

### Help request

**Problem**
 Every time I have to restart my server, Hostile mobs to false. where I have to do /mvm set monsters true every time the server restarts. If I'm not available to do the command, no one's mob grinders, and natural spawns work. 

**What I have tried**
 Looked everywhere at documentation, and nothing about it. Just everything tells me to type this command: /mvm set monsters true

**Screenshots**

**Comment by SoRadGaming** [comment] 2020-09-06 00:44
I have had the same issue since day one of 1.16

**Comment by SoRadGaming** [comment] 2020-09-06 00:47
As said here Monster World Spawn #2345, you can simply /mv reload

**Comment by darkmage4** [comment] 2020-09-06 01:00
I'll try that, and see what happens when the server restarts again.

**Comment by darkmage4** [comment] 2020-09-06 01:28
Did it, but still does it upon restart, where I have to do /mv reload again.

**Comment by benwoo1110** [comment] 2020-10-08 14:36
Duplicate of #2345

**Closed by benwoo1110** 2020-10-08 14:36 UTC
