### ISSUE TITLE
Listener? Log is telling me to notify 

### ISSUE THREAD

**Issue by therealatsuga** [Multiverse/Multiverse-Core#2074] opened 2019-08-14 16:42 UTC
[18:28:22] [Server thread/WARN]: [Multiverse-Core] "Multiverse-Core v2.5.0-b727" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

**Comment by EbonJaeger** [comment] 2019-08-14 19:45
Duplicate of #2000

**Closed** 2019-08-16 00:50 UTC
Labels: Duplicate
