### ISSUE TITLE
crash when running mv clone command inside command block

### ISSUE THREAD

**Issue by stdio2016** [Multiverse/Multiverse-Core#2167] opened 2020-02-01 09:33 UTC
looks like race condition
step to reproduce:
1. place a command block
2. type command `mv clone world w2`
3. place a button next to command block
4. click button

Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source)
	at java.util.LinkedHashMap$LinkedValueIterator.next(Unknown Source)
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1064)
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:399)
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824)
	at java.lang.Thread.run(Unknown Source)

   Running: CraftBukkit version git-Spigot-800b93f-8160e29 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT) false
   Plugins: { Multiverse-Core v4.1.0-b775 com.onarandombox.MultiverseCore.MultiverseCore [Rigby, fernferret, lithium3141, main--, dumptruckman],}

**Comment by benwoo1110** [comment] 2020-12-21 10:59
Confirmed this error occurring when a world is loaded/unloaded with command blocks, but it looks more like a spigot bug.

**Comment by benwoo1110** [comment] 2021-02-20 09:31
Duplicate of #2560

**Closed by benwoo1110** 2021-02-20 09:31 UTC
Labels: Bug: Confirmed
