### ISSUE TITLE
05.10 16:44:03 [Server] Server thread/ERROR Could not pass event PlayerJoinEvent to Multiverse-Core v2.4-b527

### ISSUE THREAD

**Issue by Ytsharpbelt636** [Multiverse/Multiverse-Core#2423] opened 2020-10-05 14:56 UTC
05.10 16:44:03 [Server] Server thread/ERROR Could not pass event PlayerJoinEvent to Multiverse-Core v2.4-b527
05.10 16:44:03 [Server] INFO org.bukkit.event.EventException: null
05.10 16:44:03 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
05.10 16:44:03 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
05.10 16:44:03 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
05.10 16:44:03 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
05.10 16:44:03 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerList.a(PlayerList.java:200) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
05.10 16:44:03 [Server] INFO at net.minecraft.server.v1_16_R2.LoginListener.c(LoginListener.java:153) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
05.10 16:44:03 [Server] INFO at net.minecraft.server.v1_16_R2.LoginListener.tick(LoginListener.java:52) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
05.10 16:44:03 [Server] INFO at net.minecraft.server.v1_16_R2.NetworkManager.a(NetworkManager.java:219) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
05.10 16:44:03 [Server] INFO at net.minecraft.server.v1_16_R2.ServerConnection.c(ServerConnection.java:130) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
05.10 16:44:03 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1126) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
05.10 16:44:03 [Server] INFO at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:352) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
05.10 16:44:03 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
05.10 16:44:03 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
05.10 16:44:03 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
05.10 16:44:03 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
05.10 16:44:03 [Server] INFO Caused by: java.lang.NullPointerException
05.10 16:44:03 [Server] INFO at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerJoin(MVPlayerListener.java:138) ~[?:?]
05.10 16:44:03 [Server] INFO at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source) ~[?:?]
05.10 16:44:03 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
05.10 16:44:03 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
05.10 16:44:03 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
05.10 16:44:03 [Server] INFO ... 14 more
05.10 16:44:03 [Connect] User Ytsharpbelt636, IP cut out
05.10 16:44:03 [PebbleHost] Ytsharpbelt636 ran command Message of the Day
05.10 16:44:03 [Server] User Authenticator #64/INFO UUID of player Ytsharpbelt636 is b4d23fa0-5544-4d28-a085-2fc52685bade

05.10 16:44:12 [Server] Server thread/INFO CURRENT: 0
05.10 16:44:12 [Server] Server thread/INFO PLAYER: 0

**Comment by benwoo1110** [comment] 2020-10-05 15:01
duplicate of #2422

**Closed by benwoo1110** 2020-10-05 15:01 UTC
