### ISSUE TITLE
Warning in console

### ISSUE THREAD

**Issue by Peppe-73** [Multiverse/Multiverse-Core#2070] opened 2019-08-10 23:32 UTC
Hi, I installed your plugin but this Warnig comes out on the console, what is it? what problems are there?
thank you
______________________________________________________________________________________________________
> [Multiverse-Core] "Multiverse-Core v4.0.0-b766" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

**Comment by axemwa** [comment] 2019-08-11 01:34
I'm getting different weird WARNS, not sure if related to multiverse tho
https://pastebin.com/FDQn8e00

**Comment by axemwa** [comment] 2019-08-11 01:46
Hmm removing chanks.dat in server/world/data folder seems to have removed my warns

**Comment by QuantumToasted** [comment] 2019-08-11 05:06
![image](https://user-images.githubusercontent.com/30324210/62830004-d05cab00-bbcb-11e9-8c2e-399488e95850.png)
can confirm, getting the same warning on a different pre-release version of MV

**Comment by Peppe-73** [comment] 2019-08-11 19:41
The file is not present CHANKS.DAT in server/world/data folde

Il
11.08.2019 03:46 Shano_dekono ha scritto: 

> Hmm removing chanks.dat in
server/world/data folder seems to have removed my warns 
> 
> --
> You
are receiving this because you authored the thread.
> Reply to this
email directly, view it on GitHub [1], or mute the thread [2].
 



Con OpenStar hai Giga, SMS e i minuti che vuoi da 4,99€ al mese, per sempre. Cambi gratis quando e come vuoi e in più hai 6 mesi di INFINTY! http://tisca.li/myopen

**Comment by Peppe-73** [comment] 2019-08-11 19:43
Where do I find the pre-release version ??

Il 11.08.2019 07:06
Daniel Jarski ha scritto: 

> [1]
> can confirm, getting the same
warning on a different pre-release version of MV 
> 
> --
> You are
receiving this because you authored the thread.
> Reply to this email
directly, view it on GitHub [2], or mute the thread [3].
 



Con OpenStar hai Giga, SMS e i minuti che vuoi da 4,99€ al mese, per sempre. Cambi gratis quando e come vuoi e in più hai 6 mesi di INFINTY! http://tisca.li/myopen

**Comment by Peppe-73** [comment] 2019-08-11 19:45
I don't understand what he wants to tell me with his answer !!!!!

Il
11.08.2019 03:34 Shano_dekono ha scritto: 

> I'm getting different
weird WARNS, not sure if related to multiverse tho
>
https://pastebin.com/FDQn8e00 [1] 
> 
> --
> You are receiving this
because you authored the thread.
> Reply to this email directly, view it
on GitHub [2], or mute the thread [3].
  


Con OpenStar hai Giga, SMS e i minuti che vuoi da 4,99€ al mese, per sempre. Cambi gratis quando e come vuoi e in più hai 6 mesi di INFINTY! http://tisca.li/myopen

**Comment by EbonJaeger** [comment] 2019-08-11 19:52
Duplicate of #2000. At least that issue number is easy to remember...

**Comment by axemwa** [comment] 2019-08-11 23:53
@Peppe-73 disregard my previous comments it turned out to be lightcleaner (another plugin) hence why I deleted my posts

**Comment by Peppe-73** [comment] 2019-08-12 09:22
????? 
then ??? solutions to my problem ???

**Comment by axemwa** [comment] 2019-08-12 11:22
No sorry I'm not a dev/author and I haven't come across this issue

**Comment by axemwa** [comment] 2019-08-12 11:23
Try going to the page Ebon referenced you to

**Comment by general2811** [comment] 2019-08-14 00:42
`[Multiverse-Core] "Multiverse-Core v4.0.0-b766" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].`

**Comment by Peppe-73** [comment] 2019-08-14 11:28
???

**Comment by Jadiction** [comment] 2019-08-16 00:48
Duplicate of #2000. (You can read more about this "issue" there.

**Closed by Jadiction** 2019-08-16 00:48 UTC
Labels: Duplicate
