### ISSUE TITLE
[Bug]: [16:36:36 INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.3.1-b861 [16:36:36 WARN]: [Multiverse-Core] "Multiverse-Core v4.3.1-b861" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--]. [16:36:36 INFO]: [Multiverse-Core] §aWe are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore. [16:36:37 INFO]: [Multiverse-Core] 3 - World(s) loaded. [16:36:37 INFO]: [Multiverse-Core] Version 4.3.1-b861 (API v24) Enabled - By dumptruckman, Rigby, fernferret, lithium3141 and main--

### ISSUE THREAD

**Issue by smscentras** [Multiverse/Multiverse-Core#2933] opened 2023-07-02 13:49 UTC
### `/mv version -p` output

https://paste.gg/p/anonymous/d622b3921e0c49ecb5668dbd4388b9b3

### Server logs

[16:36:36 INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.3.1-b861 [16:36:36 WARN]: [Multiverse-Core] "Multiverse-Core v4.3.1-b861" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--]. [16:36:36 INFO]: [Multiverse-Core] §aWe are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore. [16:36:37 INFO]: [Multiverse-Core] 3 - World(s) loaded. [16:36:37 INFO]: [Multiverse-Core] Version 4.3.1-b861 (API v24) Enabled - By dumptruckman, Rigby, fernferret, lithium3141 and main--

### Server Version

```shell
git-Paper-550 (MC:1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver /1.19.4)
```

### Bug Description

When starting server, allways this error:
[Bug]: [16:36:36 INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.3.1-b861 [16:36:36 WARN]: [Multiverse-Core] "Multiverse-Core v4.3.1-b861" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--]. [16:36:36 INFO]: [Multiverse-Core] §aWe are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore. [16:36:37 INFO]: [Multiverse-Core] 3 - World(s) loaded. [16:36:37 INFO]: [Multiverse-Core] Version 4.3.1-b861 (API v24) Enabled - By dumptruckman, Rigby, fernferret, lithium3141 and main--

### Steps to reproduce

Allways error, when start server.

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by zax71** [comment] 2023-07-02 13:51
Duplicate of #2000

**Closed by zax71** 2023-07-02 13:51 UTC
Labels: Bug: Unconfirmed
