### ISSUE TITLE
Animals set to false after server restart!!

### ISSUE THREAD

**Issue by mani00132** [Multiverse/Multiverse-Core#2439] opened 2020-10-07 20:14 UTC
# Information

Server version: git-Spigot-988b411-1f4693a (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT) 

/mv version -b: Multiverse-Core Version: [2.5-b719]
[latest.log](https://github.com/Multiverse/Multiverse-Core/files/5343562/latest.log)

Server lob in attachment

### Help request

**Problem**
When I restart the server, no animals or mobs are spawning until I run the command /mvm set animals true

**What I have tried**
I looked into the world.yml, there the animals and mob spawning is set to true, in the server.properties it is also set to true and in both files the difficulty is set to normal

**Comment by nicegamer7** [comment] 2020-10-07 20:33
I'm closing this as a duplicate of #2328. Also, your Multiverse-Core version is out of date, although, I don't think that is what is causing the issue.

**Closed by nicegamer7** 2020-10-07 20:33 UTC
