### ISSUE TITLE
MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent

### ISSUE THREAD

**Issue by malsem** [Multiverse/Multiverse-Core#2054] opened 2019-07-28 22:12 UTC
28.07 22:10:05 [Server] WARN "Multiverse-Core v4.0.0-b766" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman]

**Comment by dumptruckman** [comment] 2019-07-29 04:44
Duplicate of #2000

**Closed by dumptruckman** 2019-07-29 04:44 UTC
