### ISSUE TITLE
Warn upon start-up

### ISSUE THREAD

**Issue by Ibesh** [Multiverse/Multiverse-Core#2046] opened 2019-07-21 20:04 UTC
I am getting this warn when starting the plugin. It tells me to report it, so here I am :)

https://paste.helpch.at/qiwovakami.css

**Comment by jeannen** [comment] 2019-07-22 06:19
Same thing here !

**Comment by Jadiction** [comment] 2019-07-22 12:44
Duplicate of #2000.

**Closed by Jadiction** 2019-07-22 12:44 UTC
Labels: Duplicate
