### ISSUE TITLE
Cross-world persistent weather issue

### ISSUE THREAD

**Issue by seriosbrad** [Multiverse/Multiverse-Core#1553] opened 2015-03-02 21:57 UTC
I recently installed Multiverse to add a new Creative world but I seem to have run into a bug.

If it's raining in our main Survival world and we enter the Creative world by any means, it will also be raining there, non-stop, even commands will not stop the rain. Re-joining the server is the only fix and seems to be some sort of client-side bug?

I've tried every weather command from all of my plugins, but they don't work. Is this a Multiverse bug, or a client bug?

Details:
http://paste.enginehub.org/yz4Cd.report

**Comment by TWSSYesterday** [comment] 2015-03-03 17:17
Have you tried using /toggledownfall or using /mvm set weather false?

**Comment by seriosbrad** [comment] 2015-03-03 20:20
I have, yep. I went through literally every plugin I had, making sure I was checking the configs and commands for anything that affects weather but no-go.

**Comment by TWSSYesterday** [comment] 2015-03-03 23:57
Have you tried rebooting after using the weather setting?

**Comment by NobleStrike** [comment] 2015-03-04 01:20
Had the same issue. Issue is temp fixed with relog and is client side. I think this is a old optifine issue.

**Comment by seriosbrad** [comment] 2015-03-04 04:00
@NobleStrike I do not have any mods installed at all, purely a vanilla client
@TWSSYesterday Yep, sure have rebooted - several times

**Comment by TWSSYesterday** [comment] 2015-03-04 16:18
No worlds.yml, use the latest version then reply please :)

**Comment by NobleStrike** [comment] 2015-03-13 16:33
Where can i find the latest build?

**Comment by TWSSYesterday** [comment] 2015-03-13 19:51
http://dev.bukkit.org/bukkit-plugins/multiverse-core/

**Comment by NobleStrike** [comment] 2015-03-13 20:24
Im running Version: 2.5-b691    I do not see any other builds listed on the page. Am i missing something?

**Comment by TWSSYesterday** [comment] 2015-03-14 01:05
Hmm, I couldn't see your version for some reason. Using 1.8 Spigot?

**Comment by NobleStrike** [comment] 2015-03-19 06:24
Who me? Im running 1.8.3 spigot now and the issues is still happening.
Here is a full list of plugins updated every 24 hours
http://www.gametracker.com/server_info/ChristianCity.co:25565/server_variables/

**Comment by TWSSYesterday** [comment] 2015-03-19 13:42
Mind pastebining the entire log?

**Comment by NobleStrike** [comment] 2015-03-20 18:59
Debug for multiverse-core on https://www.dropbox.com/s/j832sb5jb97yi3m/2015-03-20-3.log.gz?dl=0
6 hour log. Not too many players on though.

**Comment by NobleStrike** [comment] 2015-03-20 19:31
Might have been patched with 1.8.3... Ill let you know

**Comment by TWSSYesterday** [comment] 2015-07-02 04:51
Issue still occuring?

**Comment by TWSSYesterday** [comment] 2016-03-05 23:03
We must assume this is no longer occurring due to a lack of further response, if the issue is still occurring, then I will re open the ticket. If it is, try updating to the latest build found on http://ci.onarandombox.com/view/Multiverse/

**Closed by TWSSYesterday** 2016-03-05 23:03 UTC
