### ISSUE TITLE
[Bug]:"Server performance will be affected"

### ISSUE THREAD

**Issue by AhmetGayaReal** [Multiverse/Multiverse-Core#3058] opened 2024-03-02 12:54 UTC
### `/mv version -p` output

https://paste.gg/4b1f4accbb264369adbb737b81fa793e

### Server logs

https://paste.gg/p/anonymous/3d7d52dc2e694f37b89ffb52c4eafe88

### Server Version

```shell
1.16.5 paper
```

### Bug Description

high use cpu

### Steps to reproduce

1. start server
2. error in console
3.high cpu ussage

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by AhmetGayaReal** [comment] 2024-03-02 12:55
[Multiverse-Core] "Multiverse-Core v4.3.12" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].

**Comment by zax71** [comment] 2024-03-02 12:58
Duplicate of #2000

**Closed by zax71** 2024-03-02 12:58 UTC
Labels: Bug: Unconfirmed
