### ISSUE TITLE
Multiverse/Multiverse-Inventories 1.16 Respawn Anchors

### ISSUE THREAD

**Issue by Syianji** [Multiverse/Multiverse-Core#2360] opened 2020-07-21 01:52 UTC
I can't say for certain which one has the issue, so i'm including both. I am also well aware that it was not updated in a while, which is why some 1.16 things don't work. But nonetheless, maybe this will spark a quick update for 1.16? During my experience, i've noticed that respawn anchors just straight up don't work with either of these plugins. You can right click it, fill it up, but when you die, you don't respawn there. I'm pretty sure its mvinventories causing the issue because the groups also handle respawn points, but i'm not sure. (you respawn at the mvworldspawn always, so it might just be the core plugin?). Its quite hard to run a survival server in just the nether, if you can't use anchors. This isn't a demand, just a recommendation, 1.16 update?

**Comment by nicegamer7** [comment] 2020-07-21 02:43
Actually, I'm going to close this as a duplicate of #2329.

**Closed by nicegamer7** 2020-07-21 02:43 UTC
Labels: Accepted, Minor Bug
