### ISSUE TITLE
Unable to delete any worlds.

### ISSUE THREAD

**Issue by ericbarbwire** [Multiverse/Multiverse-Core#1628] opened 2015-11-18 01:21 UTC
I am currently running spigot-BT45_1.8.8_10.21 and Multiverse Build # 710 from here: http://ci.onarandombox.com/job/Multiverse-Core/
MV Config: http://hastebin.com/pocanacija.vala
Worlds.yml: http://hastebin.com/urivawahig.vhdl
I recently noticed I had a few worlds built up, and decided to delete all of the unnecessary worlds that I had. The worlds I wanted to remove were titled: Road, plotme, plotmenewcurrent, Survival, Survival_the_End, and Survival_nether (It should be be noted that Survival was set to Default world since the inception of the server but more on that later).

When trying to delete a world, for example plotme, I would run the command /mv delete plotme, then /mv confirm. When trying to delete it would say world could NOT be deleted!
I then stopped the server, deleted all the worlds aside from the Survival ones, then removed the worlds from the worlds.yml block. When I started the server, the folders and world.yml regenerated.

I then from a previous Bukkit forum, decided to make a backup of the worlds.yml, whitelist the server, shut it off, delete the worlds.yml then start the server. All worlds except for Survival, Survival_the_end, and Survival_nether remained. I tried to make the changes in my backup worlds.yml file, re-upload it then start, the worlds came back after starting the server.

Also, in regards to the default worlds not deleting. I went to my server.properties file then changed level-name=Survival to level-name=Spawn. However, upon starting the server it changes back to Survival. I even download the server.properties file right after I make the change to make sure it's properly saving.
UPDATE: I was able to change the default world in the Multicraft panel.

Hope something can be done about this, thanks!

**Comment by TheEpicCooldeal** [comment] 2015-11-18 08:51
Hey Eric :)

**Comment by dumptruckman** [comment] 2016-02-04 15:18
If you delete the world folder and remote that world entirely from the worlds.yml file there is no reason Multiverse would load the world. It is impossible it would even know the world exists. It is possible, however, that some other plugin is creating the worlds and having multiverse load them.

**Comment by FernFerret** [comment] 2016-03-06 18:13
I'm going to close this one because it sounds like the issue is resolved (via update) but also that I'm not really sure what's going on.

If you can come up with a well defined test case and set of steps, we can reopen and look at it but it may even be related to #1663 and thus not really an issue, but a communication problem.

**Closed by FernFerret** 2016-03-06 18:13 UTC
