### ISSUE TITLE
Players get moved to the end after regenerating a world and restarting the server

### ISSUE THREAD

**Issue by aurorasmiles** [Multiverse/Multiverse-Core#1777] opened 2016-11-22 20:46 UTC
After regenerating a world (for example: farm) with `/mv regen` or `/mv delete` and `/mv create` and restarting the server after that, players that logged out in the world farm join directly in the world farm_the_end. This does not work if you restart your server before regenerating the world.
Neither the logfile nor the mv debug shows anything about that problem.

Steps to reproduce:
1. Player logs out in non-default world (for example **farm**)
2. You regenerate the world (using `/mv regen` or `/mv delete` and `/mv create`)
3. You restart the server
4. The player should directly join in the end (for example **farm_the_end**)

**Comment by Relaking** [comment] 2017-06-18 10:23
Issue still persists in Version 2.5.1-SNAPSHOT-b730

**Comment by benwoo1110** [comment] 2020-10-08 16:19
Can't reproduce the issue of spawning in the end world, tho I reproduce issue #2221 with the steps to reproduce stated above, so I will be closing this issue.

**Closed by benwoo1110** 2020-10-08 16:19 UTC
Labels: Bug, Unconfirmed
