### ISSUE TITLE
Server Thread WARN

### ISSUE THREAD

**Issue by Lastphysics** [Multiverse/Multiverse-Core#2104] opened 2019-09-23 17:35 UTC
Everything seems to work fine, but I got this message in cmd console : 
`23.09 19:02:40 [Server] Server thread/WARN [Multiverse-Core] "Multiverse-Core v4.1.0-b775" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].`

**Comment by blubberdiblub** [comment] 2019-09-23 19:17
The immediately following line in the log should say (if you have a sufficiently recent version of Multiverse-Core):
```
[00:12:43] [Server thread/INFO]: [Multiverse-Core] We are aware of the
warning about the deprecated event. There is no alternative that allows
us to do what we need to do. The performance impact is negligible.
```

**Comment by Jadiction** [comment] 2019-09-25 01:12
Duplicate of #2000.

**Closed by Jadiction** 2019-09-25 01:12 UTC
Labels: Duplicate
