### ISSUE TITLE
Allow spawners if monsters are off

### ISSUE THREAD

**Issue by andris155** [Multiverse/Multiverse-Core#1972] opened 2019-02-23 12:55 UTC
How to enable spawners monsters spawn if monsters are off?

**Comment by hnmitch** [comment] 2019-04-09 04:05
I've been trying to figure out this myself for the past couple of hours. Nothing I've tried works. I did manage to get eggs working but spawners won't. I was going to use this on my public skyblock server to add a regular survival world players can go to with seperate inventories.  I don't want natural spawning on the skyblock world. The spawn for skyblock has a shop that sells spawners. Any suggestions would be greatly appreciated.

**Comment by Alex-DataSIM** [comment] 2019-04-09 04:29
What makes you think this is Multiverse blocking the spawning of mobs from spawners?

**Comment by hnmitch** [comment] 2019-04-09 22:33
Because when I change the settings in the world.yml to false it starts
working again. I don't have any other plugins that control mobs spawning
except for bskyblock so it might be a compatibility issue with that. I also
googled it and several people have had the same issue. The eggs work fine
if I put the Monster_Egg in the exception list.
Its fine I removed the plugin and everything is working fine now.

**Comment by Jadiction** [comment] 2019-06-04 00:28
Duplicate of https://github.com/Multiverse/Multiverse-Core/issues/790

**Closed by Jadiction** 2019-06-04 00:28 UTC
Labels: Duplicate
