### ISSUE TITLE
[Bug]: Multiverse-Core make server LAG

### ISSUE THREAD

**Issue by AnonymeUSBC** [Multiverse/Multiverse-Core#3067] opened 2024-05-12 13:06 UTC
### `/mv version -p` output

Multiverse-Core-4.3.1, Multiverse-Core-4.3.2, Multiverse-Core-4.3.2-SNAPSHOT

### Server logs

[14:35:53 WARN]: [Multiverse-Core] "Multiverse-Core v4.3.2-SNAPSHOT-b870" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].

### Server Version

```shell
The server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
latest version
Previous version: git-Paper-309 (MC: 1.20.2)
```

### Bug Description

Tps drops from 20 to 4, server laggy significantly, Tick durations 2.0 to 250 (litteraly).

### Steps to reproduce

Just put Multiverse-Core on your server and see the magic of the lag appear (but the plugin also work fine, but adding lag to your server).

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by zax71** [comment] 2024-05-12 15:07
Duplicate of #2000 

The lag is unrelated

**Closed by zax71** 2024-05-12 15:07 UTC
Labels: Bug: Unconfirmed

**Comment by AnonymeUSBC** [comment] 2024-05-12 16:19
But here the performance impacts are really hight. Lag occurs from the moment one or more worlds are created.

**Comment by zax71** [comment] 2024-05-12 18:47
The server lagging when worlds are created is normal and unavoidable. If there is consistent lag then please send a Spark report and I will see what I can do.
