### ISSUE TITLE
Internal Server Error when entering Nether Portal that is supposedly linked to the nether. 1.16.2

### ISSUE THREAD

**Issue by MixerBlaze** [Multiverse/Multiverse-Core#2383] opened 2020-08-18 15:41 UTC
I've been at this for about an hour now, Multiverse/Multiverse Nether Portals basically crashes my server when I try to enter the nether. I have two worlds, one creative and one survival. I need the survival world to have a nether but when I link one and enter the portal, it just downright crashes everything. I've tried this with 3 different nether worlds to no avail.

**Comment by DemDumbb** [comment] 2020-08-18 22:04
I have the same issue! I think we just need to wait for an update. :(

**Comment by nicegamer7** [comment] 2020-08-18 22:26
We can't help without logs. Please upload your logs to something like Pastebin and send them here.

**Comment by tlrichar** [comment] 2020-08-20 14:59
I'm seeing this as well. Further, I have a hub-world without a nether that I used nether portals to link to the overworld nether. When I enter the nether portal on the hub world, it takes me to a nether portal on the overworld. However, when I re-enter the nether portal on the overworld, the server crashes. I'll see if I can find some logs to attach.

**Comment by DemDumbb** [comment] 2020-08-20 15:03
I’ll post my logs later tonight! I’m not near my pc at the moment.

**Comment by tlrichar** [comment] 2020-08-21 00:35
Here's a server crash log
[https://pastebin.com/GiesisCW](url)

Here's a runtime log from the time of the crash
[https://pastebin.com/L5RCAMz3](url)

**Comment by MixerBlaze** [comment] 2020-08-23 20:22
Contact me on Discord MixerBlaze#3488 if you’re interested in a solution where:
Your server has two overworlds, and only one needs access to the nether (Minecraft acts up if you go into the nether in a second world without using portal intercepts, which is what Multiverse originally excelled at fixing).
And you need traversal between worlds with player-state saving.

**Comment by nicegamer7** [comment] 2020-08-25 11:42
This looks to be a Spigot/Paper bug since the logs don't mention MV at all.

**Comment by tlrichar** [comment] 2020-08-25 14:00
> This looks to be a Spigot/Paper bug since the logs don't mention MV at all.

I'm not sure that is 100% valid since I don't see complaints from those who are using Paper without MV/MV Portals/NP. However, I did come across a post stating that dimensions/worlds are handled differently (or may have a different organization) now so maybe this is related to that. This bug could be presenting as a vanilla/paper issue but is being caused by how MV interacts with it. In the end, the simplest way to verify this would be to remove all plugins and see if nether portals work. When I get some time after work I'll see if I can do that, unless anyone here can try that and report back.

**Comment by MixerBlaze** [comment] 2020-09-09 23:11
Any luck with this? I heard someone was able to get it to work but that was just one person with barely any details.

**Comment by nicegamer7** [comment] 2020-09-10 00:28
Unfortunately, without clear steps to reproduce this issue, not much can be done. I continue to believe that this isn't a MV issue because the logs state some sort of error while ticking a block of cave_air, which is not something MV does.

**Comment by Malfrador** [comment] 2020-10-04 12:42
For me, this issue was fixed after Paper build 187, which fixed an issues with the [PortalCreateEvent](https://github.com/PaperMC/Paper/blob/44e822f7cfd46d8dfbe9f0285ee41191b496295f/Spigot-Server-Patches/0578-Fix-block-data-exception-when-cancelling-PortalCreat.patch).
I guess its fixed now and it was not a MV issue.

**Comment by benwoo1110** [comment] 2020-10-05 03:10
Looks like its fixed, will be closing the issue.

**Closed by benwoo1110** 2020-10-05 03:10 UTC
