### ISSUE TITLE
[Bug]: keepSpawnInMemory

### ISSUE THREAD

**Issue by Ozphilo** [Multiverse/Multiverse-Core#3103] opened 2024-09-10 01:46 UTC
### `/mv version -p` output

https://paste.gg/6362a3ae420c4df9aa2222d2b7ed941f

### Server logs

https://paste.gg/p/anonymous/daaf0f0d54b9499cb1569c8eb4ec0257

### Server Version

```shell
This server is running Paper version 1.21.1-74-master@971a7a5 (2024-09-08T20:24:20Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
Console
You are running the latest version
Previous version: 1.21.1-26-52ae4ad (MC: 1.21.1)
```

### Bug Description

keepSpawnInMemory is not retaining the false state, have attempted to trash the old file and let it auto populate a new file, tried adjusting with the server both down and up with stops/restarts. Problem didn't seem to be present with previous versions pre 1.20 just started to noticed upon update to 1.21 + content.

### Steps to reproduce

Shut down server
set keepSpawnInMemory: 'false'
start server
go back into worlds.yml and note the change didn't persist. 

if you repeat these steps and instead set
set keepSpawnInMemory: false (with out the 'false')
console will spit out 
`[Multiverse-Core]: Exception while loading value for keepSpawnInMemory`
I know this isn't the way was just attempting various things at this point to get it to take.

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by MadeBySaints** [comment] 2024-09-17 01:03
I can confirm this. the memory property is not saved. 
![{95C5DDA1-66C5-481F-8FD5-9C4C7CC881EA}](https://github.com/user-attachments/assets/7ea5d21b-f8e1-4baf-ac35-85abe79aac79)

![{50183A3E-31AC-473C-81B4-3B0DC9B861BF}](https://github.com/user-attachments/assets/2b4617b0-ed62-427f-a8f4-7b178f42b6d8)

**Comment by ElTuna** [comment] 2024-09-19 03:48
i'm having the same issue 😭

**Comment by zax71** [comment] 2024-09-24 22:04
Duplicate of #3072

**Closed by zax71** 2024-09-24 22:04 UTC
Labels: Bug: Unconfirmed

**Comment by TylorTurner** [comment] 2024-10-25 20:04
Same issue, any resolution?

**Comment by zax71** [comment] 2024-10-25 20:22
Update Paper, as stated in the previous conversation
