### ISSUE TITLE
Plugin Error in Console

### ISSUE THREAD

**Issue by MinecraftMarcus1** [Multiverse/Multiverse-Core#2069] opened 2019-08-10 01:54 UTC
[Server] Server thread/WARN "Multiverse-Core v4.1.0-SNAPSHOT-b772" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

**Comment by Jadiction** [comment] 2019-08-10 19:44
Duplicate of #2000.

**Closed by Jadiction** 2019-08-10 19:44 UTC
Labels: Duplicate
