### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Spelicious** [Multiverse/Multiverse-Core#2705] opened 2021-09-20 20:30 UTC
There is a bad command for multiverse that ruins the server.
There has been a person throwing
`/mv ^(.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.++)$^`
and server instantly crashes after that.

**Comment by MrPranklez** [comment] 2021-09-20 20:32
Join the discord or download the latest version from spigot. The issue should be resolved with those builds

**Comment by nicegamer7** [comment] 2021-09-20 20:32
Duplicate of #2703.

**Closed** 2021-09-20 20:32 UTC

**Comment by benwoo1110** [comment] 2021-09-22 04:31
For those using older multiverse builds and can't update for whatever reason: https://www.spigotmc.org/resources/multiverse-patches.96390/
