### ISSUE TITLE
[Bug]: Multiverse-Core v4.3.9 has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method but the event is Deprecated.

### ISSUE THREAD

**Issue by nonfreegithub** [Multiverse/Multiverse-Core#2939] opened 2023-07-25 23:28 UTC
### `/mv version -p` output

https://paste.gg/p/anonymous/1726304dbde54e4790ec9c94d38d26f6

### Server logs

http://ix.io/4Bv3

### Server Version

```shell
Bukkit Version: 3836-Spigot-3374045-08ec344 (MC: 1.20.1)
Built with BuildTools #160 https://hub.spigotmc.org/jenkins/job/BuildTools/160/
```

### Bug Description

Error output in server log: http://ix.io/4Bv3

### Steps to reproduce

Start a server with multiverse core installed.
Read the log

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by NeverGrowUp** [comment] 2023-07-25 23:34
The last 3 sentences of your error log is your answer.
This will be resolved in a future release.

**Comment by nicegamer7** [comment] 2023-07-28 14:03
Closing as a duplicate of #2000.

**Closed by nicegamer7** 2023-07-28 14:03 UTC
Labels: Bug: Unconfirmed
