### ISSUE TITLE
[Bug]: second end world created without exit portal

### ISSUE THREAD

**Issue by antiGriefer** [Multiverse/Multiverse-Core#2776] opened 2022-06-08 18:32 UTC
### `/mv version -p` output

https://paste.gg/p/anonymous/277bee97d6514334a2c29a876ae8ab91

### Server logs

https://paste.gg/p/anonymous/5fcb608721e0465ab13382002a84c789

### Server Version

```shell
1.19
```

### Bug Description

When I create  a second end world, it will create everything, except a exit portal in the middle and a enderdagon is also missing. The name of the second end world is:"private_the_end'' . 

Sidenote: deleting this end and recreating it also doesnt work.

### Steps to reproduce

1. /mv create private_the_end end
2. /mvtp private_the_end
3. Fly to the middle and see, the exit portal is missing
4. Enderdragon is also gone

EDIT:
Just building a exit portal urself on 0,0 also doesnt work. The self summoned (/summon) dragon wont accept it/use it and the portal cant be used to summon a dragon using end crystals
### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [x] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by resi23** [comment] 2022-06-09 07:44
can confirm
![Uploading Bild_2022-06-09_094408531.png…]()

**Comment by JustAHuman-xD** [comment] 2022-06-09 22:44
This is also the case on our server running 1.17 running MV v.4.2.2
![image](https://user-images.githubusercontent.com/65748158/172957457-b3d9ff3f-ee0a-458e-83ee-e59e91e8942b.png)

**Comment by Nerdtendo** [comment] 2022-06-13 17:34
Same issue on 1.19.

**Comment by ChuckLingBao** [comment] 2022-06-17 21:37
Can confirm issue on 1.19 with Multiverse-Core-4.3.2-SNAPSHOT as the only plugin installed on the server.

**Comment by Jeppa** [comment] 2022-06-17 23:05
Yes, can confirm this...
WorldServer does not initiate an EnderDragonBattle in 1.19...

But as far as I can see, this is NOT a Multiverse-bug, but Spigot/Paper itself!

**Comment by zax71** [comment] 2022-06-18 13:19
![image](https://user-images.githubusercontent.com/67716263/174439492-3d422b85-9d5f-4b83-9560-4134aa740e49.png)
Can confirm.

**Comment by Jeppa** [comment] 2022-06-18 13:51
Latest Spigot from today should have the fix for this...

**Comment by Nerdtendo** [comment] 2022-06-18 16:04
> Latest Spigot from today should have the fix for this...

Does this mean spigot that _will be_ released today or spigot that _has been_ released today because I am unable to find an update from today.

**Comment by Jeppa** [comment] 2022-06-18 22:53
If you mean Spigot itself, you should know you have to compile it yourself !
That compile will have the fix... ;)

**Comment by Crnojevic** [comment] 2022-06-19 12:26
Confirmed working in the latest Spigot - just waiting on [Paper PR #8015](https://github.com/PaperMC/Paper/pull/8015) now and this issue will be solved!

**Comment by zax71** [comment] 2022-06-20 20:19
Paper has pushed [#31](https://papermc.io/downloads) so I will close this issue.

**Closed by zax71** 2022-06-20 20:19 UTC
Labels: Bug: Confirmed, Type: Upstream
