### ISSUE TITLE
MultiVerse Inventory

### ISSUE THREAD

**Issue by NoExtraSauce** [Multiverse/Multiverse-Core#2184] opened 2020-03-05 20:34 UTC
Not sure if bug, but when 'use_game_mode_profiles' is set to true, switching between gamemodes teleports you to two different locations instead of keeping you were you are on switch.

**Comment by sjoll** [comment] 2020-03-27 18:14
I don´t have problem with this, but when i use the "/mvinv toggle last_location" command, and enabling it, then it seems to change my location switching between gamemodes, i assume it saves my location data separately depending on players gamemode.

**Comment by sjoll** [comment] 2020-04-03 10:06
Hello, any news on this?

**Comment by benwoo1110** [comment] 2020-04-03 10:14
Ensure that you set `use_game_mode_profiles: false` in config.yml.

**Comment by nicegamer7** [comment] 2020-06-07 10:21
This is a duplicate of Multiverse/Multiverse-Inventories#108. I'll be closing it as such, but make sure to follow the linked issue!

**Closed by nicegamer7** 2020-06-07 10:21 UTC
Labels: Bug, Unconfirmed
